### ISSUE TITLE
The circuit will disappear and nothing further is possible. Must exit circuit to continue.

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#1]
To re-create:
Open new circuit
Pan fully to lower right or left corner
Create a LED matrix
Create another LED matrix (if in the lower left, create a third matrix)
Pan further to the lower right or left
Circuit will be out of view.

If circuit is deleted, new circuit will not work. The app must be shut down and restarted after deletion.

**Comment by pawelsurowka** [comment]
Thank you for report, we will investigate this issue.

**Comment by Proto-App** [comment]
Thank you for report, we will investigate this issue.

**Comment by Proto-App** [comment]
@KarlW100  Fixed in version 0.15.1

**Comment by KarlW100** [comment]
Great, Issue closed.
