### ISSUE TITLE
Beta Gain on Transistors

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#100]
Hi,
I'm here to ask about a problem i have since i'm not sure if it is a bug or i'm just not comprehending how it works
Because if i'm not mistaken, the bete is calculated by passing the Current on Ic over Ib
Current on collector divided Current on Base
Wich should give us the gainance
If we pass 10mA on the base of a transistor and it has a 100 beta 
We can amplify that current signal in 1A
1000mA = 10mA times Beta(in this case 100)
But when tried to make it work on a circuit it doesn't seem to be correct
![Screenshot_20211207-212652](https://user-images.githubusercontent.com/71222618/145126974-3fc68212-ba9f-4799-ba1a-7d5210f83856.png)

Actually, trying to replicate some Amplifiee Circuit like Class A or B or even AB never seemed to work
So maybe is an error of how the transistor works?
Maybe because of the base having resistence 0 and the same goes to the colector?
Idk, so i thought maybe you guys could help
Not really urgent ,just saw this curious, since no one seems to report this "bug"(?
I imagined that by changing the Beta setting on the osciloscope it would be visualy perseptible how it affects the current on the led

**Comment by YukarinnAM** [comment]
Also,i forgot to add
Maybe this is just a simple variable bug
In wich the Beta setting is a constant with a value of 100 of 200 and because of it
We are unable to modify it manually on the app
That seems like one of the most possible scenario
That or maybe the transistor beta was gonna be imprement but the setting was forgotten and it passed unwatched for noone seem to know how it works lol

**Comment by Proto-App** [comment]
Hello @YukarinnAM 

In your example transistor base has 100uA. 100uA * 100 Beta can  produce 10mA. We created this circuit and we think that it looks correct, please check our screenshot: 
![device-2021-12-11-192322](https://user-images.githubusercontent.com/63373346/145687438-0361539a-6656-4f6d-b4c9-6d1dbf8832dc.png)

**Comment by YukarinnAM** [comment]
That's correct
The thing is
That the beta feels very buggy
If you change thw beta with the circuit on, it doesn't have an apparent visual change on the oscilloscope
On your simulation we see that
100μA × 100 Beta = 10mA
Wich is correct, 10000(μ) / 100(μ) = 100 Beta
But if you have 1mΩ on the circuit after the emitter you still receive only receive current as if the beta was 100
Independiently of how is set the transistor
Here some examples
![Screenshot_20211213-034838](https://user-images.githubusercontent.com/71222618/145765631-8ffc364b-3fe5-42c9-be25-5d9e89d5bda5.png)
![Screenshot_20211213-034843](https://user-images.githubusercontent.com/71222618/145765637-8b63cc4d-ea41-48d5-9483-7d3b98e4ee99.png)
![Screenshot_20211213-034853](https://user-images.githubusercontent.com/71222618/145765641-2f5048b4-9322-4efb-a5bc-2a3a4a509204.png)
1m * 1000 ≠ 100m
1m * 0 ≠ 100m
1m * 294 ≠ 100

As you can see the beta doesn't affect the Ei/Bi relation
Wich it 100, so because of this, i believe that beta is like a constant, but irl this isn't the case, different transistors have different Gainance or Beta
you can try this with this circuit, changing the beta setting ,it will not change how current on the base affects current on the emitter

**Comment by YukarinnAM** [comment]
I hope my explaination was detailed enought

**Comment by Proto-App** [comment]
Ok, now we get it. It might be lack of beta update in transistor. We have to verify it. Thanks for explanation!

**Comment by YukarinnAM** [comment]
Of course of course no problem
Also, testing a thing 
It seems that, if you change beta
And go reset the app ot just the circuit from leaving it to the main menu, then entering on the circuit again, it works properly
So yes, it totally seems like a beta update problem
Once again, thanks for the great support!

**Comment by sachchidanand265** [comment]
I have faced the same problem. Looking forward to see this problem solved.
![Screenshot_2021-12-15-15-09-12-902_com proto circuitsimulator](https://user-images.githubusercontent.com/69332354/146162736-1c3d2c80-9ff1-4454-8c9e-a731865a41b0.jpg)
![Screenshot_2021-12-15-15-09-53-779_com proto circuitsimulator](https://user-images.githubusercontent.com/69332354/146162751-f41f31fb-e7e0-41f2-bb5d-230188574f3a.jpg)

**Comment by Proto-App** [comment]
This bug is verified and will be fixed in next release.

**Comment by Proto-App** [comment]
@YukarinnAM  @sachchidanand265 
Fixed in v1.3.0
