### ISSUE TITLE
Missing upgrades

### ISSUE THREAD

**Issue by Gralloc** [Proto-App/Proto-Android#101]
Hi, I purchased the full upgrade today containing all the individual packs, however they are not showing up, I have uninstalled and reinstalled, rebooted and whatever else I could think of but Proto continues to ask for payment, please help.

**Comment by Gralloc** [comment]
Just to let you know that I eventually fixed the issue by pressing  buy again and it righted itself.

**Comment by Proto-App** [comment]
@Gralloc 
This is the first time when we received this kind of issue. PROTO is receiving info about your purchased products from Google framework and we rely on it. Good to hear that you received product, thank you for support!
