### ISSUE TITLE
7 Segment Decoder no parameters 

### ISSUE THREAD

**Issue by Gralloc** [Proto-App/Proto-Android#102]
The 7 Segment Decoder has no way of changing the output states, so A to F are always set at high 5v G and the other outputs are always set at 0v, this makes the decoder near useless.

**Comment by Proto-App** [comment]
@Gralloc 
Thank you for report, we will verify it.

**Comment by Proto-App** [comment]
@Gralloc 
Could you post screenshot of your circuit? We verified it on our side and it works ok, check screenshot below:
![device-2021-12-14-104153](https://user-images.githubusercontent.com/63373346/145973456-6626c18b-6099-4933-a4c3-c7cc05373438.png)

**Comment by Gralloc** [comment]
Hi, guys, guess what, you are correct, it was my fault and I had made a bad connection and did not spot it. 
Thanks for your quick help, and for this software app, it will be a great help in getting me back into electronic circuits after a very long  illness. 
Cheers
Graham

Sent from the all-new AOL app for Android 
 
  On Tue, 14 Dec 2021 at 9:43, PROTO ***@***.***> wrote:   


@Gralloc
Could you post screenshot of your circuit? We verified it on our side and it works ok, check screenshot below:


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
