### ISSUE TITLE
Circuit example for more gates, also new error

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#104]
Hello!
With the new update
And because you guys told me to give you this when this update came out
Here you have the more gates circuit example
https://www.protosimulator.com/share?circuit=More_Gates_1640735118843
![Screenshot_20211228-204922](https://user-images.githubusercontent.com/71222618/147615348-11530867-8b13-432b-88ee-1a5955465bb7.png)

Also, would like to show a new error, that's most likely because it creates an .zip of the circuit wich ends up getting detected as a "circuit"
![Screenshot_20211228-204555](https://user-images.githubusercontent.com/71222618/147615289-b8dd6af2-15c6-45f1-b9d9-48d3b8c40853.png)

For some obvious reasons i believe that i didn't created the .zip

**Comment by Proto-App** [comment]
Hello @YukarinnAM 
Thank you for circuit! We will add it in next update.

In case of issue ;) Could you share any scenario to reproduce this case?

**Comment by YukarinnAM** [comment]
Thank you very much for your work!

Of course
All i did was actually simply press the share button, haven't pressed again tho
Could maybe be a only once error
Also, once i entered again on the up
It seems like it dissapeared

Also, i tried to repeat the steps i made
Wich was simply press the share button
But doesn't seem to appears again, weird
Sadly it seems there is no way to reproduce the error, perhaps trying many times

**Comment by Proto-App** [comment]
Ok, probably we have one scenario when it can be possible :+1: 

By the way, we would like to use your nickname and put it in description (author label), is it ok for you?

**Comment by YukarinnAM** [comment]
Oh, of course
I have no problem with that ^^
I would be honored!

**Comment by Proto-App** [comment]
Example is present in version 1.4.0.
We fixed issue with zip visibility in one case.
