### ISSUE TITLE
Time scale

### ISSUE THREAD

**Issue by MontMontgomery** [Proto-App/Proto-Android#106]
Hi, with an question

How do i set correctly my time scale in my simulation?

There is 2 configurations for timing : Time Interval and Simulation Velocity

If i want to set my time interval on my circuit to 1s, how can i make it?

**Comment by Proto-App** [comment]
Hi @MontMontgomery 
You can set time scale from right menu, its called "Time step". You can set 500ms as max time step. In some cases big time step can cause serious problems with simulation (non linear elements - diodes, transistors etc) and can introduce unstable results. To avoid bad user experience we decided to allow max 500ms.
