### ISSUE TITLE
Batteries

### ISSUE THREAD

**Issue by Aquarius12104** [Proto-App/Proto-Android#109]
Is there batteries? 

@Proto-App

**Comment by Aquarius12104** [comment]
I apologize for not using a label. I do not use github very often let alone post so I'm still newer to all of this

**Comment by Proto-App** [comment]
@Aquarius12104 App doesn't have battery but there is ticket for it:  https://github.com/Proto-App/Proto-Android/issues/58

**Comment by Aquarius12104** [comment]
@Proto-App 

Thanks
