### ISSUE TITLE
two fingers "pinch" gesture on scope for changing display timing.

### ISSUE THREAD

**Issue by Bushmills** [Proto-App/Proto-Android#110]
I'm currently using a combination of simulation step and simulation speed for getting the scope display right, not sure whether that's supposed to be done that way.  However, being able to allow by gesture to narrow or widen the displayed scope traces will make it clear that that'd be the proper method to do so.

**Comment by Proto-App** [comment]
Yes, we have such feature for future update.

**Comment by foresterr** [comment]
Pinch to zoom would be nice and very mobile-y, but a way to precisely set scope's time base by just inputting it is even more essential, imo.

**Comment by Bushmills** [comment]
Zoom per gesture was of course implying (albeit not explicitely saying so) that time per division, as you're used from a real scope, would be shown too.

**Comment by Proto-App** [comment]
Implemented in version 1.8.0
