### ISSUE TITLE
Examples for Adder, Latch, PISO Register and Multiplexer

### ISSUE THREAD

**Issue by Sven130889** [Proto-App/Proto-Android#112]
Hello, these components are completely new to me and I would like to know exactly how to use them and how to build meaningful circuits with them.

**Comment by Bushmills** [comment]
would these possibly help?
[Half adder](https://en.wikipedia.org/wiki/Adder_(electronics)#Half_adder)  
[Full adder](https://en.wikipedia.org/wiki/Adder_(electronics)#Full_adder)  
[Addition](https://en.wikipedia.org/wiki/Addition)

**Comment by Proto-App** [comment]
@Sven130889 Some examples use adders, latches and registers.
