### ISSUE TITLE
More efficient testing

### ISSUE THREAD

**Issue by Lkn7** [Proto-App/Proto-Android#114]
When I'm trying out my circuits, if there is a switch i always need to double tap it to select and then toggle it.
This sometimes leads to me accidentally moving the component and it is just annoying in general.
I propose that components can't be moved around when the circuit is running. It can only be edited when we press pause.

**Comment by Proto-App** [comment]
Hello @Lkn7 
We have some idea to introduce lock button or switch, but we have to think about possible solutions. As a workaround you can zoom in circuit and then it is easier to toggle switch.

**Comment by Proto-App** [comment]
@Lkn7 
Version 1.6.0 has additional button that can be used with switches.
