### ISSUE TITLE
Will you bring this app to pc

### ISSUE THREAD

**Issue by Paul74uk** [Proto-App/Proto-Android#118]
This app was just what I was looking for and has helped me build real life circuits. I would ideally like something like this on pc for a number of reason like screen size and better control being my main desire.

**Comment by Proto-App** [comment]
Hi @Paul74uk probably we won't release it on desktop. One of the reason is that we know only Android platform and we are good at it. Maybe we will release our app on iOS in future. By the way you can use app on tablet, this device shows real potential of our app.
