### ISSUE TITLE
LED Blow too Easy

### ISSUE THREAD

**Issue by Awen2345** [Proto-App/Proto-Android#122]

**Comment by Proto-App** [comment]
@Awen2345  Please describe your issue.

**Comment by Awen2345** [comment]
![Screenshot_2022-03-14-20-55-09-15_33e07244786ec8aea651eea65ad70e5e.jpg](https://user-images.githubusercontent.com/87870432/158186569-338a3248-35e8-4706-8f89-5ae0d7f09269.jpg)
Hi Proto Team , Can add Voltage range 
Example
LED Red 1.63 - 2.03 volts
LED Yellow 2.10 - 2.18 volts
LED Orange 2.03 - 2.10 volts
Etc...

**Comment by Awen2345** [comment]
This is LED colour Voltage
![9afe777f7796f0f14acb6f2781bcda35.jpg](https://user-images.githubusercontent.com/87870432/158188132-0f63d405-b323-4419-a657-f2d75aab8c8f.jpg)
