### ISSUE TITLE
More examples with 555 ic

### ISSUE THREAD

**Issue by MontMontgomery** [Proto-App/Proto-Android#124]
![Screenshot_20220315-180259_P R O T O.png](https://user-images.githubusercontent.com/93541980/158472072-5fb46115-a823-4cd9-aed1-3e9eb07b3f5d.png)

[https://www.protosimulator.com/share?circuit=555_IC_1647378107652]()

3 basic operation mode
Astable, monoestable, FF SR

Good work on creating this app!

**Comment by Proto-App** [comment]
@MontMontgomery 
Thank you for circuits! Can we use your nick name as an author name in description in PROTO?

**Comment by MontMontgomery** [comment]
> @MontMontgomery 
> Thank you for circuits! Can we use your nick name as an author name in description in PROTO?

For sure!

**Comment by MontMontgomery** [comment]
[https://www.protosimulator.com/share?circuit=555_IC_1647441806904]()

Some minor improvements
