### ISSUE TITLE
Osciloscope Graphical bug

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#130]
For some reason the osciloscope signal gets out of the marc/space 
![Screenshot_20220328-192444](https://user-images.githubusercontent.com/71222618/160497352-045d90e1-3e55-4d52-b2f0-52b66a908eeb.png)

the bug seems to appear even after exiting the proyect and opening it again
https://www.protosimulator.com/share?circuit=Circuit_99_1648506401316

**Comment by Proto-App** [comment]
Thank you for report. Strange graphical issue, we will check your circuit.

**Comment by Proto-App** [comment]
@YukarinnAM 
Fixed in version 1.9.1
