### ISSUE TITLE
LEDs need adjustable voltage. 

### ISSUE THREAD

**Issue by SK-Infidel** [Proto-App/Proto-Android#133]
All we have are the common 2.2v 20ma 3/5mm type LEDs. High power LEDs need to be configurable. There are LEDs now that are 3.3v and 700ma, that are single LEDs, not microarrays.

We should be able to configure all the properties on a data sheet. 

>

**Comment by Proto-App** [comment]
@SK-Infidel 
Implemented in version 1.9.1
