### ISSUE TITLE
Discreet voltage dividers

### ISSUE THREAD

**Issue by SK-Infidel** [Proto-App/Proto-Android#137]
See discreet diode bridges

**Comment by Proto-App** [comment]
@SK-Infidel  Could you give real life example of this component?

**Comment by SK-Infidel** [comment]
Sorry. Should have said resistor networks.

See MPMT1001AT1

**Comment by SK-Infidel** [comment]
Just thought it would help to save workspace real estate.

**Comment by Proto-App** [comment]
@SK-Infidel You can save some space and use potentiometer component.
