### ISSUE TITLE
Add a Chinese translation

### ISSUE THREAD

**Issue by Cang-Yue** [Proto-App/Proto-Android#14]
Hello
can you add a Chinese translation to the PROTO. Give me the string.xml file and I can translate some sentences for you for free.

**Comment by Proto-App** [comment]
Hello @Cang-Yue 
Thank you for your proposal, please contact us by email: proto.playstore@gmail.com

**Comment by Proto-App** [comment]
@Cang-Yue 
Implemented in version 0.19.0
