### ISSUE TITLE
Issue with themes and exportations

### ISSUE THREAD

**Issue by MontMontgomery** [Proto-App/Proto-Android#142]
Hello!
The new themes are so good, but the 'light' and 'solarized' are a bit tricky to see buttons and switches 
![Screenshot_20220506-114317_P R O T O.png](https://user-images.githubusercontent.com/93541980/167156803-09255973-314d-40dd-9dca-5638665f3c06.png)
Here you can see the switch from a relay.
Also a dark-green color in wires, and a bigger outline for components should be a little easier to see.

And about export to pdf, png, jpeg.
It should export the whole circuit, not just the fraction that you are seeing in the moment of the export.

Keep the good work! Great app!

**Comment by Proto-App** [comment]
@MontMontgomery  thank you for report, we will improve it.

**Comment by Proto-App** [comment]
@MontMontgomery 
Fixed in version 1.9.1

**Comment by MontMontgomery** [comment]
Neat!
