### ISSUE TITLE
Example submit

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#143]
Hi proto team
i wanted to make a example submit to the apparently growing list
This time it is a MOS Inverter RLC Oscilator
it is actually used on many Microcontroler ICs to run their clocks so i thought it would be interesting to replicate
Because it also worked with the already integrated Inverter component
i decided the MOS equivalent of it (So you can also have different voltage source)
because i couldn't replicate a real XCrystal i simply used an RLC Circuit
but it should also work(and is designed to) work with XCrystals (this -> ---|[]|--- )
![Screenshot_20220510-223434](https://user-images.githubusercontent.com/71222618/167752035-bd812a4e-1252-4f0c-8b13-1c6f3f509511.png)

along with a Simple OverVoltage Protection (with zeners) so you don't burn irl Mosfets in case you want to replicate it

In theory i can go from 200KHz to even 10MHz but is not tested the limits

It outputs an square wave
i planned to make use of a counter and a DAC to turn it into a ramp wave but decided to just use an LED 

https://www.protosimulator.com/share?circuit=RLC_Oscilator_1652232986371

Here you have the circuit, also the last update was simply awesome tho i found a certain bug i'll report in another issue 

Thanks for you hard work as always!

**Comment by Proto-App** [comment]
@YukarinnAM 
Implemented in version 1.9.1
