### ISSUE TITLE
Scope visual bug

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#144]
A common visual bug that happens when using the scope with a modified data lenght or at least that's how i forzed it to happen

![Screenshot_20220510-225443](https://user-images.githubusercontent.com/71222618/167753277-f1a4c134-daa2-4bf4-acc7-f144e09a80c3.png)

looks like a bug that appears whenever you switch the scope from voltage to current abruptly
like it doesn't recognize when is the scope limit and stops rending the wave there
but is easy to solve by just unproving the component and prove it again on the current measured value

![Screenshot_20220510-230157](https://user-images.githubusercontent.com/71222618/167754072-0d6cbbab-a973-4983-bde4-e86eb7c0a593.png)

Select the first component as Voltage

![Screenshot_20220510-230205](https://user-images.githubusercontent.com/71222618/167754081-078c628b-f5dc-4f8e-96fa-5d3eda4c6221.png)

Select second component as current

**Comment by Proto-App** [comment]
@YukarinnAM 
Thank you for report, we discovered this bug yesterday :disappointed: it will be fixed in next release.
