### ISSUE TITLE
Add Crystal Oscillator

### ISSUE THREAD

**Issue by Awen2345** [Proto-App/Proto-Android#145]
This is Crystal Oscillator Equivalent
You Can add my Circuits this picture or link to example
![Screenshot_2022-05-29-11-25-10-47_33e07244786ec8aea651eea65ad70e5e.jpg](https://user-images.githubusercontent.com/87870432/170852229-e5160873-bb0f-4875-b884-ba591aa58d6e.jpg)
https://www.protosimulator.com/share?circuit=Circuit_1_1653862877031
I Hope You implement Crystal Oscillator 
In next update app

**Comment by Proto-App** [comment]
@Awen2345 Thank you for example!

**Comment by Proto-App** [comment]
Implemented in version 1.9.1
