### ISSUE TITLE
Add 7400 and 4000 series Integrated   Circuits

### ISSUE THREAD

**Issue by Awen2345** [Proto-App/Proto-Android#146]
if you add IC 7400 and 4000 series IC it is very important for us

**Comment by Proto-App** [comment]
@Awen2345 
Could you name the most important ICs from 7400 and 4000 family?

**Comment by Awen2345** [comment]
@Proto-App basically 7400 and 4000 series ICs are implemented

**Comment by Awen2345** [comment]
@Proto-App basically 7400 and 4000 series ICs are implemented

**Comment by Proto-App** [comment]
@Awen2345 
7400 TTL series will be available in version 1.16.0
4000 CMOS series will be available in version 1.17.0

**Comment by Awen2345** [comment]
Thank You , I still Waiting next Update @Proto-App

**Comment by Proto-App** [comment]
CMOS implemented in 1.17.0

**Comment by reklaw29** [comment]
This is still missing a lot of 74xx series chips.
The one I needed in particular is 74ls76
