### ISSUE TITLE
Make Open Source

### ISSUE THREAD

**Issue by electron271** [Proto-App/Proto-Android#148]
I understand that it's hard to make the app open source, but you can still get money from the libraries by having some parts not open source. You can also maybe add a custom plug-in or library interface that you can pay to use.

**Comment by electron271** [comment]
I really want to buy some of the libraries and addons, but I would feel better if it was open source. You could also add donations as another source of money, I would definitely donate if it was open-source

**Comment by Proto-App** [comment]
@electron271 
Hi, we don't have a plan to open source our application. Donations are agains Google developer policy.

**Comment by electron271** [comment]
Alright, that sucks that google doesn't let you do that.. I still really like Proto and use it to experiment around without risking blowing my breadboard up
