### ISSUE TITLE
Scope Time

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#149]
Hi there
This is a function request
I was using a capacitor try measuring how much amp hour on a range of voltages it has
And when using the scope i thought about a function that would really come it handy
and that would be that of being able to see how much time is it when you select two point
like this
![Screenshot_20220626-011624](https://user-images.githubusercontent.com/71222618/175799216-2074c1cf-9365-4e80-b43e-e4d70378d2b2.png)
And that it shows somewhere (maybe on the other side of the screen undeneath the scopes) how much is this time period
for measuring frecuencies and charge speed is really really usefull
And it feels like something that should be there

Thanks for the great job and reading this
Have a great day!

**Comment by Awen2345** [comment]
did you forget the trigger lock on the oscilloscope , it's very important?

**Comment by Awen2345** [comment]
did you forget the trigger lock on the oscilloscope , it's very important?

**Comment by YukarinnAM** [comment]
Excuse me but... what is a trigger lock?

**Comment by Awen2345** [comment]
Trigger controls allow you to stabilize repetitive waveforms and capture single-shot waveforms. The trigger makes repetitive waveforms appear static on the oscilloscope display by repeatedly displaying the same portion of the input signal
![Screenshot_2022-06-27-07-02-29-77.jpg](https://user-images.githubusercontent.com/87870432/175839154-04fab2dd-e652-41b2-9440-8c114b161b0d.jpg)

**Comment by YukarinnAM** [comment]
Ohhh you are right, that would be incredibly usefull
and now that i remenber that exists on real osciloscopes

**Comment by Proto-App** [comment]
@YukarinnAM 
Great idea! We will add this feature.

@Awen2345 
Could you make separate issue with your request?

**Comment by Proto-App** [comment]
@YukarinnAM 
Implemented in version 1.10.0
