### ISSUE TITLE
Voltmeter and Ammeter recommendation 

### ISSUE THREAD

**Issue by AdmiralSharky49** [Proto-App/Proto-Android#151]
I would like the voltmeter and Ammeter to be able to be switched between measuring dc voltage/current, but also measure AC voltage/current peak, rms, and peak-to-peak.

**Comment by Proto-App** [comment]
@AdmiralSharky49 
Sure, we can add p-p, rms and other stuff to voltmeter and ammeter.

**Comment by Proto-App** [comment]
@AdmiralSharky49 Implemented in version 1.12.0
