### ISSUE TITLE
Add new Examples 

### ISSUE THREAD

**Issue by Awen2345** [Proto-App/Proto-Android#157]
1. 741 Inverting Amplifier
![741 Inverting amp.jpg](https://user-images.githubusercontent.com/87870432/179436552-e215255b-b706-4d72-9707-cb607a3d696f.jpg)
Link:https://www.protosimulator.com/share?circuit=741_Inverting_amp_1658110240975

2. 741 Non Inverting Amplifier
    ![741 Non Inverting.jpg](https://user-images.githubusercontent.com/87870432/179436769-e44b2c28-58f7-43cb-b627-12caa749d066.jpg)
Link:https://www.protosimulator.com/share?circuit=741_Non_Inverting_1658111176850

3.741 Slew Rate
![741 Slew Rate.jpg](https://user-images.githubusercontent.com/87870432/179436916-47f5163e-a8d4-4a16-be21-9c7b6b7e0bb3.jpg)
Link:https://www.protosimulator.com/share?circuit=741_Slew_Rate_1658110292162

4. Square Wave Generator
![Square Wave Gen.jpg](https://user-images.githubusercontent.com/87870432/179436851-f61452ba-5b44-4c74-a809-686c1fbd9b90.jpg)
Link:https://www.protosimulator.com/share?circuit=Square_Wave_Gen_1658110381289

5. Sine Wave Generator
 ![Screenshot_2022-07-19-11-46-09-49_33e07244786ec8aea651eea65ad70e5e.jpg](https://user-images.githubusercontent.com/87870432/179667019-ad19dfcc-f347-41e9-84ef-58e34e87c3bd.jpg)
Link: https://www.protosimulator.com/share?circuit=Sine_Wave_Gen_1658206048618

6. Triangle Wave Generator
![Triangle Wave Gen.jpg](https://user-images.githubusercontent.com/87870432/179439976-bd897561-7485-4ca5-a696-6e2cd0fff123.jpg)
Link:https://www.protosimulator.com/share?circuit=Triangle_Wave_Gen_1658110417831

7. Sawtooth Generator
![Sawtooth Gen.jpg](https://user-images.githubusercontent.com/87870432/179440052-914ab62c-bdf5-4fec-8ab9-4e62185690f0.jpg)
Link:https://www.protosimulator.com/share?circuit=Sawtooth_Gen_1658110164656

**Comment by Awen2345** [comment]
8. CMOS VCO
![Phase Locked Loop.jpg](https://user-images.githubusercontent.com/87870432/179441726-b0934be3-b1c0-4617-aedf-f7d1ee85924c.jpg)
Link:https://www.protosimulator.com/share?circuit=CMOS_VCO_1658115297933

9. AC 220v Dimmer
![Dimmer.jpg](https://user-images.githubusercontent.com/87870432/179441754-d734c67c-2a14-468a-98bf-64e45e57e06d.jpg)
Link:https://www.protosimulator.com/share?circuit=Dimmer_1658115356831

**Comment by Proto-App** [comment]
@Awen2345 
Thank you for stunning examples! Could we use your nickname in app as an author of examples?

**Comment by Awen2345** [comment]
Yes i sure

**Comment by Awen2345** [comment]
Hello @Proto-App 
i made a large circuit is IC Internal Schematic L3803 

![Screenshot_2022-08-12-18-39-45-42_33e07244786ec8aea651eea65ad70e5e.jpg](https://user-images.githubusercontent.com/87870432/184347593-9f0b489e-c181-4f72-aaa8-5bf64754dc7a.jpg)
![Screenshot_2022-08-12-18-39-58-95_33e07244786ec8aea651eea65ad70e5e.jpg](https://user-images.githubusercontent.com/87870432/184347609-1efb78f5-043a-4e31-b862-698873d0ae94.jpg)
![Screenshot_2022-08-12-18-40-04-11_33e07244786ec8aea651eea65ad70e5e.jpg](https://user-images.githubusercontent.com/87870432/184347627-a5815d38-0f78-4cf6-ba7c-5fd77bf248ae.jpg)
I made a circuit from :
![Screenshot_2022-08-12-18-41-57-00.jpg](https://user-images.githubusercontent.com/87870432/184347704-98ea2947-5f9a-426d-868b-4147691f81e4.jpg)
Link : https://www.protosimulator.com/share?circuit=L8038_1660304422135
Add my Examples to proto app

**Comment by Proto-App** [comment]
@Awen2345 
Examples added in 1.11.0
