### ISSUE TITLE
Separate oscilloscope

### ISSUE THREAD

**Issue by thelearn-tech** [Proto-App/Proto-Android#16]
Have a separate oscilloscope will help to probe different components individually and will be even more better if it has multiple channels for example two or three channels

**Comment by Proto-App** [comment]
If we understand correctly this is behavior similar to https://github.com/Proto-App/Proto-Android/issues/6

**Comment by thelearn-tech** [comment]
Could be I am not too sure .
By the way the best spice simulator ever on Android

**Comment by Ashwin-droid** [comment]
> Could be I am not too sure .
> By the way the best spice simulator ever on Android

Yes it is getting there. Very good efforts. Good job, team proto keep it up

**Comment by HubbsInHobby** [comment]
I hope the scope can work for both voltages and currents of different components instead of switching between voltage and amperage.

Example: After adding a couple of voltage-scopes on my circuit, I added a current-scope. All the display switched to current and no more voltages is in view!

**Comment by Proto-App** [comment]
Implemented in version 1.15.0
