### ISSUE TITLE
Display of the "9" without the bottom line

### ISSUE THREAD

**Issue by Sven130889** [Proto-App/Proto-Android#161]
The 7 segment decoder shows the 9 without the lower segment.  Is this a different display format or a bug?  So far I only knew that WITH the bottom line.
![Screenshot_20220724-194923_P R O T O](https://user-images.githubusercontent.com/94050749/180659922-111cd265-16f5-449f-8f88-965618a0fb1f.jpg)

**Comment by Proto-App** [comment]
@Sven130889 
You are right, D segment is missing... We have new version already in rollout so this will be fixed in later release. Thank you for report.

**Comment by Proto-App** [comment]
@Sven130889 
Fixed in 1.11.0
