### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by Sven130889** [Proto-App/Proto-Android#162]
Full Substractor
![full_substractor_P R O T O](https://user-images.githubusercontent.com/94050749/181078493-afcda509-421e-45f1-83ab-1c990a82282d.jpg)
https://www.protosimulator.com/share?circuit=Full_Substractor_1658858617471

Multiplexer
![multiplexer_P R O T O](https://user-images.githubusercontent.com/94050749/181078499-6c36cc06-f346-4936-b92f-a35bef9ebe15.jpg)
https://www.protosimulator.com/share?circuit=Multiplexer_inside_1658858664022

NUM Keyboard
![num_keyboard_P R O T O](https://user-images.githubusercontent.com/94050749/181078503-4c743842-3808-46cb-ab8a-9086337b392d.jpg)
https://www.protosimulator.com/share?circuit=NUM_Keyboard_1658858698873

PISO Register
![piso_register_P R O T O](https://user-images.githubusercontent.com/94050749/181078509-737e71b3-deb6-4f60-be65-76cbf0255623.jpg)
https://www.protosimulator.com/share?circuit=PISO_Register_inside_1658858754393

Random Generator
![random_generator_P R O T O](https://user-images.githubusercontent.com/94050749/181078513-2511e5ee-6b73-47df-bab8-bedf5bf09628.jpg)
https://www.protosimulator.com/share?circuit=Random_Generator_1658858797837

Roulette
![roulette_P R O T O](https://user-images.githubusercontent.com/94050749/181078519-c41efe28-e326-4f97-bbd3-dc88d25998cc.jpg)
https://www.protosimulator.com/share?circuit=Roulette_1658858841381

Traffic Light
![traffic_light_P R O T O](https://user-images.githubusercontent.com/94050749/181078520-be52efc6-a3ec-458d-b90b-48a74645d0ed.jpg)
https://www.protosimulator.com/share?circuit=Traffic_Light_1658858900527

**Comment by Proto-App** [comment]
@Sven130889 
Thank you again! Great circuits!

**Comment by Proto-App** [comment]
Implemented in v1.11.0
