### ISSUE TITLE
I hope to add the support of the full Chinese coding and the Addons tab will not be loaded out

### ISSUE THREAD

**Issue by AromanRon** [Proto-App/Proto-Android#164]
1、When I use MT manager for localized translation, there will be garbled code when setting the name of electronic components。
2、Addons tab always loading, even using VPN

**Comment by Proto-App** [comment]
@AromanRon 
Is there any reason to hide addons tab?

**Comment by AromanRon** [comment]
> @AromanRon 有什么理由隐藏插件选项卡吗？

Sorry,maybe I didnot express clearly.Its not about hiding the Addons tab.When I opened the Proto APP,the Addons tab has a funnel that keeps spinning.But I waited a long time and its always been like this,still spinning

**Comment by Proto-App** [comment]
@AromanRon Are your from China? As we know Google does not support in app purchases in this country.
