### ISSUE TITLE
Add My Examples About Power Converter 

### ISSUE THREAD

**Issue by Awen2345** [Proto-App/Proto-Android#169]
1. Buck Converter 
![Screenshot_2022-09-03-20-52-27-35.jpg](https://user-images.githubusercontent.com/87870432/188273766-ce89bee9-c3ed-4bf8-bcc8-3df8adf48afb.jpg)
https://www.protosimulator.com/share?circuit=Buck_Converter_1662213301136

2. Boost Converter
![Screenshot_2022-09-03-20-52-14-21.jpg](https://user-images.githubusercontent.com/87870432/188273834-ed9b2a3b-3210-4c8c-b4e5-1c6f2a3d94c0.jpg)
https://www.protosimulator.com/share?circuit=Boost_Converter_1662213166671

3.Buck Boost Converter
![Screenshot_2022-09-03-20-52-20-77.jpg](https://user-images.githubusercontent.com/87870432/188273871-7e400b2f-0f3a-4eb7-95a7-aaa2f782524e.jpg)
https://www.protosimulator.com/share?circuit=Buck_Boost_Converter_1662213280509

4.SEPIC Converter
![Screenshot_2022-09-03-20-52-34-49.jpg](https://user-images.githubusercontent.com/87870432/188273917-56fafed2-066b-4e03-8919-26c0236565b2.jpg)
https://www.protosimulator.com/share?circuit=SEPIC_Converter_1662213412478

5.CUK Converter
![Screenshot_2022-09-03-20-57-17-89.jpg](https://user-images.githubusercontent.com/87870432/188273934-2714cdb8-4205-4db6-a025-f612112bd480.jpg)
https://www.protosimulator.com/share?circuit=Cuk_Converter_1662213392814

 6. Flyback Converter
![Screenshot_2022-09-04-10-32-21-16.jpg](https://user-images.githubusercontent.com/87870432/188297723-0967544a-e5b9-44fc-9257-6047ccc3db67.jpg)
https://www.protosimulator.com/share?circuit=Flyback_Converter_1662266405328

7.Forward Converter
![Screenshot_2022-09-04-11-06-56-51.jpg](https://user-images.githubusercontent.com/87870432/188297736-0edafc89-4786-47ee-847e-332eeb5578bf.jpg)
https://www.protosimulator.com/share?circuit=Forward_Converter_1662266561026

8.Push Pull Converter
![Screenshot_2022-09-04-11-23-59-27.jpg](https://user-images.githubusercontent.com/87870432/188297780-1e40885b-cb92-4ec7-bea4-9498027104ed.jpg)
https://www.protosimulator.com/share?circuit=Push_Pull_Converter_1662266606625

9. 12v to 220v Inverter
![Screenshot_2022-09-04-11-35-56-42.jpg](https://user-images.githubusercontent.com/87870432/188297796-41d8217b-87d4-409c-8d56-3c1b56d64bc7.jpg)
https://www.protosimulator.com/share?circuit=12v_to_220v_Inverter_1662266659924

**Comment by Proto-App** [comment]
@Awen2345 Thank you, we will add examples in next update.

**Comment by Awen2345** [comment]
do you know about IC UC3843? @Proto-App

**Comment by Proto-App** [comment]
Yes, we know about this IC

**Comment by Awen2345** [comment]
Can you implement the UC3843 IC?

**Comment by Awen2345** [comment]
Can you implement the UC3843 IC?

**Comment by Proto-App** [comment]
@Awen2345 examples implemented in version 1.12.0
