### ISSUE TITLE
Cannot input capacitance with decimal.

### ISSUE THREAD

**Issue by wuyongzheng** [Proto-App/Proto-Android#170]
I want to have a 3.3uF capacitor, but I can only have 3 or 4. I can't even put two capacitors in parallel. It complaints C3 is shorted.

**Comment by Proto-App** [comment]
@wuyongzheng 
Do you use input dialog to set capacitor value? By default capacitors does not have internal resistances and that is why you have message about shorted component. You can turn on "Wires resistance"  from settings panel (swipe from left), then you will be able to run simulation without issues.

**Comment by wuyongzheng** [comment]
> 
Thanks for the response. I used the dialog. I mean click on the number and cannot type in the decimal point. Wire resistance completely distorted the simulation result. But I get the idea, I can add a small serial resistor to the capacitor.

**Comment by Proto-App** [comment]
Yes, you can add small resistors. Ok, on values other than F you can not type ".", we will try to fix this design flaw.

**Comment by Proto-App** [comment]
@wuyongzheng 
Implementd in version 1.18.0
