### ISSUE TITLE
Access saved circuits on another device

### ISSUE THREAD

**Issue by mastershel** [Proto-App/Proto-Android#172]
Please consider adding a feature to access saved circuits on one device on another device.

**Comment by Proto-App** [comment]
@mastershel  Thank you for request, we are working hard on this feature and global circuit library for community.

**Comment by mastershel** [comment]
I am glad to hear that. Thank you also for developing a very useful app.

**Comment by Proto-App** [comment]
@mastershel 
In version 1.21.0 you can export whole workspace and import it on another device.
