### ISSUE TITLE
The reload fab button is not discharging capacitor

### ISSUE THREAD

**Issue by yaras** [Proto-App/Proto-Android#175]
Hello,

Thanks for the application, it is really nice, simple and powerful!

One thing that I may have missed is that when I hit reload (double arrows button on left side), capacitors remain "charged".

Is there a way of reloading the circuit so that capacitors are discharged?

Regards

**Comment by Proto-App** [comment]
@yaras 
Thank you for report, we will check this behavior during reload.

**Comment by kpribylov** [comment]
Hi, I have the same issue on 1.23.0 for Android 13

**Comment by Proto-App** [comment]
Hello @kpribylov 
Thank you for reminder. Fix is not present, we have to do it probably in version 1.25.0

**Comment by Proto-App** [comment]
@yaras @kpribylov 
Fixed in version 1.25.0

**Comment by Proto-App** [comment]
@kpribylov 
Fixed in 1.25.0
