### ISSUE TITLE
Cannot open example because of digital pack

### ISSUE THREAD

**Issue by HyVong007** [Proto-App/Proto-Android#177]
I have bought the Bundle pack. But when i try to open the "Rainbow Light Effect" example, it says "The circuit contains unknown component: Digital pack" and the example is grey color. Please fix it !

**Comment by Proto-App** [comment]
@HyVong007 
Could you send your order ID? It starts with GPA- prefix. Do you have access to all components during fresh simulation?

**Comment by HyVong007** [comment]
> 
Transaction id: GPA.3303-9611-4504-96427

Now i can open "Rainbow light effect" example, it is strange, i dont know why !
I can use all circuit components from all packs.
I think this bug rarely happens but you should
check again, thank you !

![Screenshot_20221124-062543_P_R_O_T_O](https://user-images.githubusercontent.com/20169967/203664067-ae5f2275-eaeb-46a1-b24d-8564a21e6e8b.png)

**Comment by Proto-App** [comment]
@HyVong007 
Great! Sometimes Google sends info about purchased products with some delay (Google is responsible for in app purchase payment process). We think this case occurred here (we had few reports with similar situation).
