### ISSUE TITLE
Addons already bought

### ISSUE THREAD

**Issue by Messy1983** [Proto-App/Proto-Android#186]
I bought the bundle add on and switched devices but now it wants me to buy the add-ons again

**Comment by Proto-App** [comment]
Hi @Messy1983 
You need to use the same Google account, all purchases are tied to Google account.

**Comment by Messy1983** [comment]
I used the same Google account and redownloaded using the same account and they still didn't come up

**Comment by Proto-App** [comment]
Coul you reinstall PROTO? Few users had similar issue and reinstall solved their issue.

**Comment by Proto-App** [comment]
@Messy1983 
Did you solve your issue?
