### ISSUE TITLE
Specific cmos ics

### ISSUE THREAD

**Issue by kozll6** [Proto-App/Proto-Android#187]
It would be great to have pin for pin (like the 555) cmos ics instead of just the generic mux/demux, shift register, hex inverter etc. Also, a vactrol where the ldr would react to the led in the circuit mockup instead of from the external phone sensor

**Comment by Awen2345** [comment]
7400 TTL series will be available in version 1.16.0
4000 CMOS series will be available in version 1.17.0

**Comment by Proto-App** [comment]
@kozll6 
Cmos addon is almost done :checkered_flag:

**Comment by Proto-App** [comment]
CMOS implemented in 1.17.0
