### ISSUE TITLE
Please Add UJT 2N2646 particular component.

### ISSUE THREAD

**Issue by Notno5538** [Proto-App/Proto-Android#189]
Add 2N2646 UJT for it's characteristic.
And add something like that can use universal component like all components parameters changing buttons etc.
Provide all components characteristic default circuit in app which use and practical done in colleges and schools like Diode, transistor , LDR,T network Delta network , ujt, scr phase control etc, 
I know very well above all circuits are easy create in app using some steps, but it takes time and students don't have much time ,

**Comment by Proto-App** [comment]
@Notno5538  You can build these circuits in our app.
