### ISSUE TITLE
Buying bundle pack not working

### ISSUE THREAD

**Issue by VGumny** [Proto-App/Proto-Android#196]
I bougt the bundle pack but it doesn't work.

**Comment by Proto-App** [comment]
Hi @GuVi171819 could you give your order ID? It starts with GPA- prefix.

**Comment by Proto-App** [comment]
@GuVi171819 
Please reopen if you have any issues with bundle pack access.

**Comment by VGumny** [comment]
still not working.
where can i find my purchase ID

**Comment by Proto-App** [comment]
You can find it on your Gmail account. Google always sends confirmation with order ID.

**Comment by VGumny** [comment]
bougt it again,
here's the order number:
GPA.3306-4071-1711-92648

**Comment by Proto-App** [comment]
Thank you, do you have access to addon content?

**Comment by Proto-App** [comment]
@GuVi171819 
As we can see payment is ok but your order is not verified by our application. Could you uninstall PROTO and install it once again from Google Play store?

**Comment by VGumny** [comment]
NO,
OTHERWISE I WOULDN'T HAVE CONTACTED YOU.
I apologize for being rude.

**Comment by VGumny** [comment]
my Email software mixed up the Mails.
It's still not working.

**Comment by VGumny** [comment]
i already told you, but here:
GPA.3306-4071-1711-92648

**Comment by VGumny** [comment]
mixed up again. I'm sorry
