### ISSUE TITLE
Tapping a switch multiple times triggers zoom

### ISSUE THREAD

**Issue by 64-Tesseract** [Proto-App/Proto-Android#20]
This issue is a simple but pretty irritating one; tapping once to select a switch and again to use it, or trying to use a switch multiple times, triggers the zoom control. It'd be really good to check if taps are selecting a component before zooming.

**Comment by Proto-App** [comment]
Yes, you are correct. Will be fixed in upcoming releases.

**Comment by Proto-App** [comment]
Fixed in v0.21.0
