### ISSUE TITLE
Add New Examples About TTL Gates

### ISSUE THREAD

**Issue by Awen2345** [Proto-App/Proto-Android#202]
1. 74LS00
![74LS00.jpg](https://user-images.githubusercontent.com/87870432/217554576-a40d1ef1-8ce9-4597-b9fb-8d19997bd7a2.jpg)

Link: https://www.protosimulator.com/share?circuit=74LS00_1675865471470

2. 74LS02
![74LS02.jpg](https://user-images.githubusercontent.com/87870432/217557427-193630a9-4efc-4da9-b32a-34476f34cb53.jpg)

Link:
https://www.protosimulator.com/share?circuit=74LS02_1675865792750

3.74LS08
![74LS08.jpg](https://user-images.githubusercontent.com/87870432/217557587-c097119e-6605-4886-8e8b-8300617bf520.jpg)

Link:https://www.protosimulator.com/share?circuit=74LS08_1675865522838

4. 74LS04
![74LS04.jpg](https://user-images.githubusercontent.com/87870432/217558579-9d1ddb70-d1fa-4793-8956-22d644d8337e.jpg)

Link:
https://www.protosimulator.com/share?circuit=74LS04_1675894295084

5.74LS32
![74lS32.jpg](https://user-images.githubusercontent.com/87870432/217559399-fa000c2a-60ef-4bfe-8ba4-c6c86947913e.jpg)

Link:
https://www.protosimulator.com/share?circuit=74lS32_1675865606227

**Comment by Proto-App** [comment]
@Awen2345 
Thank you. We will add all of your examples in next release.

**Comment by Proto-App** [comment]
@Awen2345 
Added in version 1.25.0
