### ISSUE TITLE
[Help] How to change the Lux level for the Photoresistor

### ISSUE THREAD

**Issue by BruhXD451** [Proto-App/Proto-Android#208]
I have tried many different ways to change the lux level for the photoresistor to use & test on my circuit. The problem is that I cannot find any way that will affect the Lux level and cause the resistance to change.

**Comment by Proto-App** [comment]
Hello @BruhXD451 
Photoresistor uses phone's light sensor to increase/decrease resistance value. You can point source of light on your device, then resistance should decrease.
