### ISSUE TITLE
Idk how to explain it

### ISSUE THREAD

**Issue by PythonVladuxa12345** [Proto-App/Proto-Android#21]
![Screenshot_2021-02-23-22-37-59-063_com proto circuitsimulator](https://user-images.githubusercontent.com/67973022/108898638-7a721b80-7628-11eb-8798-ef37c0fb6761.jpg)

**Comment by PythonVladuxa12345** [comment]
LED is glowing red because wavelength is 700

**Comment by Proto-App** [comment]
Capacitor C1 is shorted and probably this causes wrong state of your circuit. Try to connect resistance between V1 and C1.
