### ISSUE TITLE
[Feature request] plugins

### ISSUE THREAD

**Issue by Ashwin-droid** [Proto-App/Proto-Android#22]
I think you should add a feature in which you could add components by third party plugins like if you want phase shifting transformer or a center tapped transformer you could install a plugin (like a pack of all types of transformer which you design or a third party) and expose some api to do that (which should be designable by a individual).

**Comment by Ashwin-droid** [comment]
Or probably installing components pack from a url

**Comment by Ashwin-droid** [comment]
@Proto-App please respond for #22 and #18

**Comment by Proto-App** [comment]
For now we won't implement 3rd party components, simply because we don't have enough resources to develop such thing like thoughtful API. Furthermore our app is not popular enough and we prefer to develop more basic things during alpha stage.

**Comment by Ashwin-droid** [comment]
@Proto-App did you ment to close issue #4
