### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FogyX** [Proto-App/Proto-Android#224]
It would be nice to add such a feature as simulating electromagnetic induction. It will make it possible to construct such schemes as, for example, high frequency generator. It also could be a good thing for learning this phenomenon.

**Comment by Proto-App** [comment]
@FogyX 
Could you give example of it?

**Comment by FogyX** [comment]
@Proto-App 
![Screenshot_20230424-205239](https://user-images.githubusercontent.com/93732719/234034273-cb95e315-d6cb-4c31-a4dd-bbc033bd9447.png)
I meant something like this

**Comment by Proto-App** [comment]
Ok, now we get it. It could be quite complicated to implement. For now you can simulate it probably with transformer.

**Comment by FogyX** [comment]
Okay, good luck then!
