### ISSUE TITLE
Unable to watch the transients on the scope properly

### ISSUE THREAD

**Issue by suryadeep56** [Proto-App/Proto-Android#24]
Hi, I found that you cannot go back to see the transients on the scope. I tried to simulate a simple RC circuit on it with reduced simulation speed. Is it possible to add something like where you can simulate it for a particular amount of time or go back the scope and have a look at the transients after pausing the simulation. 
Also, once the RC circuit reached steady-state, you cannot reset the circuit and it remains in the steady state. Please add a few features to observe transient circuits.

**Comment by Proto-App** [comment]
Hello @suryadeep56 

Thanks for suggestions! We know that now you can not see historical values in scope, it will be available in addon (ability to record samples).

In second case we will add RESET button.

**Comment by Proto-App** [comment]
RESET button is available in v0.23.0
