### ISSUE TITLE
Lost in translation

### ISSUE THREAD

**Issue by Bushmills** [Proto-App/Proto-Android#240]
German localisation:
Term for a digital latch should remain latch. "Verriegelung" is not used for such electronic components.

**Comment by Proto-App** [comment]
Hi @Bushmills  thank you for report, we rely on translations because German is not our native language. We will fix this and your second report. If you have any tricky translations please let us know. Best Regards PROTO Team

**Comment by Proto-App** [comment]
@Bushmills 
Fixed in version 1.21.0
