### ISSUE TITLE
Share circuit link brings to app download page

### ISSUE THREAD

**Issue by Whosdeez** [Proto-App/Proto-Android#242]
Even when the app is downloaded, clicking on a link to a shared circuit doesn't have any effect other than bringing up the Play Store app download button

**Comment by Proto-App** [comment]
@Whosdeez  Thank you for report. Could you share your device model and Android version?

**Comment by Jurgen2003** [comment]
That's a phone setting. The proto app is not standard for that link 
![Uploading Screenshot_20230524_125851_Settings.jpg…]()

**Comment by Whosdeez** [comment]
@Proto-App I'm using a Samsung S10 Lite running Android 13.
A friend of mine is also running Android 13, on a Samsung A53 5G. He encountered the same issue.
Thanks @Jurgen2003 your solution works.
It would be great if www.protosimulator.com web links were activated by default.
Though, note that pasting the link in a browser still doesn't redirect to the app. It has to be CLICKED on (for example, in a discord message, Word document or e-mail) in order to open the app and add the circuit automatically.

**Comment by Whosdeez** [comment]
![Screenshot_20230524_205100_Settings](https://github.com/Proto-App/Proto-Android/assets/134500894/4bda26ec-28e1-4c6f-8ad0-fdd8fc1562a3)
![Screenshot_20230524_205106_Settings](https://github.com/Proto-App/Proto-Android/assets/134500894/5633accf-c1ea-42ce-b267-eb52418ebdc6)

**Comment by Jurgen2003** [comment]
Dear @Whosdeez I had the same problem and found out about this. I read your problem and recognized it right away nice that it works for you too 

Greetings Jurgen

**Comment by Proto-App** [comment]
@Jurgen2003 Thank you for help! Interesting because on our Motorola G82 this setting is turned on by default :thinking: We assume that this might be some kind of customization on Samsung devices or maybe this is related to Android 13. Our Moto has Android 12. We will investigate it  :+1:

**Comment by Proto-App** [comment]
It is probably customized by device provider and we can not fix it.
