### ISSUE TITLE
I bougt the bundle pack but it doesn't work.

### ISSUE THREAD

**Issue by LucasPaivaSilva** [Proto-App/Proto-Android#244]
I bougt the bundle pack but it doesn't 
GPA.3360-4392-7700-55011

![SmartSelect_20230524_232839_P R O T O](https://github.com/Proto-App/Proto-Android/assets/37738982/219a6580-0125-4569-a36c-07c65c6a9420)
![SmartSelect_20230524_232824_P R O T O](https://github.com/Proto-App/Proto-Android/assets/37738982/56b9feaa-de12-42b9-9e1b-ba1503c255d9)

**Comment by Proto-App** [comment]
Hi @LucasPaivaSilva 
Could you uninstall and then install PROTO again? Very strange issue, we can't reproduce it on our devices 😐

**Comment by LucasPaivaSilva** [comment]
Sure, i did that,  same problem Enviando Screen_Recording_20230525_153139_P R O T O.mp4 …

**Comment by Proto-App** [comment]
@LucasPaivaSilva 
You don't have this addon because Google validation is unsuccessful  ?! Could you clear app data once again and run PROTO?

**Comment by Proto-App** [comment]
If it won't help then we will return your payment.

**Comment by LucasPaivaSilva** [comment]
You mean my payment validation (the one with my ID)?, it was just confimed now, but i still cannot use the addon. I tried cleaning the local cache and reinstaling multiple times. On this, i noticed that everytime i download from playstore it does come with my circuits, do you keep any cache/data in the cloud? how could i clean that?

**Comment by LucasPaivaSilva** [comment]
btw, some extra information
device: Galaxy Tab S6 Lite
android version: 13 (5.1 on OneUI)

**Comment by Proto-App** [comment]
@LucasPaivaSilva 
Hmm, that is very strange that you have previous circuits. Each "clean" installation should have always empty workspace, maybe this is the key related to your issue. We think that PROTO has previous state of this addon but we don't have any Samsung device with Android 13 :disappointed:  ... We checked logs from our server and we can't see request from your device with your order ID. Do you execute exact steps like in [https://www.samsung.com/us/support/answer/ANS00077611/](https://www.samsung.com/us/support/answer/ANS00077611/) ?

**Comment by Proto-App** [comment]
By the way we don't use any cache, typically we save circuits in app standard directory that is available only for our application. It should be removed when you clear app's data.

**Comment by Proto-App** [comment]
@LucasPaivaSilva any news in your case?

**Comment by LucasPaivaSilva** [comment]
ow, i am sorry, i tried again a few times, in one try i opened the app after cleaning the data/cache to see if there was some circuit remaining (tried a few times before too) and then the app crashed. After opening again all the addons show as avaliable, so i dont have a problem anymore

**Comment by LucasPaivaSilva** [comment]
but if it is of your interest i could help to search on this, because there is a bug somewhere (maybe on android itself or samsung cache management)
Thanks for the help! i am going to change my review on playstore, i loved the app, happy that i can use the addons now! c:

**Comment by Proto-App** [comment]
@LucasPaivaSilva 
Great news! We are almost 100% sure that this issue was related to Android/Samsung and it might be some kind of cache. We don't have any Smasung device but maybe we should have one :)
