### ISSUE TITLE
unable to see the numbers ( voltage , resistance and other elements ) 

### ISSUE THREAD

**Issue by MahdiMalik33** [Proto-App/Proto-Android#25]
![IMG_20210309_001720_237](https://user-images.githubusercontent.com/80289410/110383045-d26b4200-806c-11eb-8908-4dd78ae81731.jpg)

can't see results even that I have enabled everything ( show voltage , show current , show values...)

**Comment by Proto-App** [comment]
Could you change your phone language to english and check value labels? It is strange that you have numbers inside component label (R1 etc) and value label is empty.

**Comment by MahdiMalik33** [comment]
yes ut worked after changing the language from arabic to english 
![Uploading IMG_20210312_213825_607.jpg…]()

**Comment by Proto-App** [comment]
Currently we support english and chinese simplified.
