### ISSUE TITLE
PC VERSION?

### ISSUE THREAD

**Issue by V037** [Proto-App/Proto-Android#252]

**Comment by Proto-App** [comment]
@V037 We don't have any plans to release PC version, we have iOS version planned.

**Comment by V037** [comment]
ok, but then start thinking to a pc version please, it is quite hard use my big fingers on a small smartphone for wire everything that I place inside the circuit

**Comment by Proto-App** [comment]
@V037 
We strongly recommend bigger devices like tablets, much easier to use PROTO.
