### ISSUE TITLE
Tutorial Course

### ISSUE THREAD

**Issue by ondrejholan** [Proto-App/Proto-Android#253]
I am total noob and I would like to learn how to make circuits. There is lot of examples, but some of them are too complex for beginner. 

It would be really helpful to have something like course, where you would go from absolute basics to complex circuits and scripting.
I imagine something that would go through all the components and gradually unlock and introduced them, what they do, how to (not) use them and guide you through it.

It could be another addon I would gladly pay for, maybe it could be easier to add some documentation of the parts when you press and hold onto them. Yes I can find it on the internet what everything does, but it would be more convenient to have it in the app and I mostly try this app in the bus when I don't have internet connection.

**Comment by Proto-App** [comment]
Hi @ondrejholan 
Thank you for suggestion. It would be nice to have complete howto for each component. Our main target for now is to add more components. At least we will try to add basic tutorials in near future. We won't charge for those materials, our mission is to give ability to learn basic electronics :)

**Comment by Amonia69420** [comment]
i just make a capacitor example (the example shows that capacitor can store energy/electricity)

**Comment by Proto-App** [comment]
@ondrejholan @Amonia69420 
Next release (next week) contains basic video tutorials about different parts of PROTO app (not about components). But slowly we will expand topics on components/circuits. Thank you for suggestions.

**Comment by Proto-App** [comment]
@ondrejholan @Amonia69420 
Basic tutorials implemented in version 1.24.0
