### ISSUE TITLE
Pacote Bundle

### ISSUE THREAD

**Issue by presydenty** [Proto-App/Proto-Android#255]
Olá. Comprei o pacote Bundle, mas ainda assim, para abrir alguns exemplos, ainda é pedido para comprar um determinado pacote que já está incluído no pacote Bundle.

**Comment by Proto-App** [comment]
Olá, você deve ter acesso a todos os exemplos. Questão muito estranha. Você poderia desinstalar o PROTO e instalar novamente? O aplicativo deve atualizar seus complementos comprados.

**Comment by presydenty** [comment]
Desinstalei e voltei a instalar. O problema persiste.

**Comment by presydenty** [comment]
O problema foi resolvido. Obrigado.
