### ISSUE TITLE
Export/import workspace

### ISSUE THREAD

**Issue by stevemilkins** [Proto-App/Proto-Android#261]
Hi, moving to new tablet, how do I import workspace? Thank you

**Comment by Proto-App** [comment]
Hello @stevemilkins 
Firstly you have to export your workspace (click on dots on top app bar and choose Export workspace option). You should get link to exported workspace, save this link. Then run PROTO on second device and click on link (you can send it via email). PROTO will import all of the items.

**Comment by Proto-App** [comment]
Please keep in mind that link is valid for 6 months and you require at least version 1.21.0 to export/import workspace.
