### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Jurgen2003** [Proto-App/Proto-Android#263]
Dear proto 
 There are some problems in this version so import is not possible comes this message. On 4g on wifi in the previous version it did work on these networks. Furthermore I have sometimes a circuit suddenly has no voltage and does not come back how is this possible? 
 Greetings Jurgen 
![Screenshot_20230716_184131_P R O T O.jpg](https://github.com/Proto-App/Proto-Android/assets/128260279/f6f4c9eb-a8f8-42ba-b928-94c91f72eb6d)

**Comment by Proto-App** [comment]
Hello @Jurgen2003 
Strange, we did not change anything from last version related to connectivity. Could you check Addons tab under 4G network?

**Comment by Jurgen2003** [comment]
Hello @Proto-App so as I said it is with 4g and wifi .  Greetings jurgen

**Comment by Proto-App** [comment]
@Jurgen2003 Could you check Addons tab under 4G/wifi network?

**Comment by Jurgen2003** [comment]
Hello @Proto-App so as I said it is with 4g and wifi .   


I can inmport and export a workshop but not 1 circuit  

Greetings jurgen

**Comment by Proto-App** [comment]
@Jurgen2003 we can't reproduce it on our side.

**Comment by Jurgen2003** [comment]
@Proto-App Yes, of course I understand, but I find it strange and I want to tell you. 
  Greets jurgen

**Comment by Ryan27777** [comment]
I have bug

**Comment by Ryan27777** [comment]
I'm confused why the 4000 cmos IC hasn't opened even though I already bought it

**Comment by Ryan27777** [comment]
![Uploading Screenshot_20230725-164744_P R O T O.jpg…]()
