### ISSUE TITLE
Buzzer Problem

### ISSUE THREAD

**Issue by Doni7888** [Proto-App/Proto-Android#267]
My buzzer just sound beep beep beep.. in audio wav file input, mic and Toy Organ scematic is the problem in my phone? My OS Android V 5.1
![Screenshot_2023-07-23-13-18-52_1](https://github.com/Proto-App/Proto-Android/assets/140300341/419773e6-c3ab-49b5-b4ad-a34e4a02a516)

**Comment by Proto-App** [comment]
Hello @Doni7888 
Yes, buzzer has only single sound. We will add speaker component soon.

**Comment by Doni7888** [comment]
Thank you for information
