### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by herlanaditya71** [Proto-App/Proto-Android#273]
how to use the temperature sensor and pressure sensor is there a tutorial for that?

**Comment by Proto-App** [comment]
Hello @herlanaditya71 
Temperature and pressure sensors read data from physical sensors from your device (sometimes device does not have pressure sensor). If you place sensor then it should work out of the box. You can read signal from it (voltage value)

**Comment by herlanaditya71** [comment]
is there a video tutorial for using the temperature sensor and pressure
sensor?

Pada tanggal Sen, 21 Agu 2023 19.46, PROTO Team ***@***.***>
menulis:

**Comment by Proto-App** [comment]
Video is not available now.
