### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by herlanaditya71** [Proto-App/Proto-Android#274]
after updating JavaScript can not be used

**Comment by Proto-App** [comment]
Could you give us more detailed description?

**Comment by herlanaditya71** [comment]
yesterday there was an update for the proto application, after I updated
it, after updating the JavaScript application it could not be used, before
updating JavaScript it could be used

Pada tanggal Sen, 21 Agu 2023 19.47, PROTO Team ***@***.***>
menulis:

**Comment by Proto-App** [comment]
Strange, we have newest version and JS components are available. Could you give your order ID of JavaScript purchase?

**Comment by herlanaditya71** [comment]
ID :
G3tvAJZqyxq6EvjaiCyNUbs


Pada tanggal Sen, 21 Agu 2023 19.53, PROTO Team ***@***.***>
menulis:

**Comment by herlanaditya71** [comment]
ID :
161702585025921115

Pada tanggal Sen, 21 Agu 2023 20.08, Herlan Aditya ***@***.***>
menulis:

**Comment by herlanaditya71** [comment]
SN TRANSACTIONS : ATVuotmzv9sS1

Pada tanggal Sen, 21 Agu 2023 20.10, Herlan Aditya ***@***.***>
menulis:

**Comment by Proto-App** [comment]
@herlanaditya71 
Order ID starts with GPA- prefix

**Comment by herlanaditya71** [comment]
Pada tanggal Sel, 22 Agu 2023 00.24, PROTO Team ***@***.***>
menulis:

**Comment by Proto-App** [comment]
@herlanaditya71 Do you have order ID?
