### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Yunhanar** [Proto-App/Proto-Android#275]
![IMG_20230822_201300](https://github.com/Proto-App/Proto-Android/assets/123705471/b69c0ca5-ec70-4203-b926-7096aa0a5dac)

**Comment by Proto-App** [comment]
@Yunhanar 
Thank you for report. Could you share your device model and android version?

**Comment by Yunhanar** [comment]
Device : Vivo Y12s
Android version 11

**Comment by Proto-App** [comment]
@Yunhanar 
Could you share one of the items from PROTO or whole workspace?

**Comment by Yunhanar** [comment]
Like this? Sorry i cant upload a videos, gmail prevented me.

Pada tanggal Rab, 23 Agu 2023 03.05, PROTO Team ***@***.***>
menulis:

**Comment by Proto-App** [comment]
You can tap on "Export workspace" and share link with us.

**Comment by Yunhanar** [comment]
https://www.protosimulator.com/share?workspace=workspace_14ac8dc9-712b-4181-aac6-9d70b3d65aad_1692788815114

Pada tanggal Rab, 23 Agu 2023 17.59, PROTO Team ***@***.***>
menulis:

**Comment by Proto-App** [comment]
We can't reproduce it on our devices. It must be connected to your vivo device. It has specific GPU MCU (PowerVR) and probably it causes this issue. We can't fix it.
