### ISSUE TITLE
Cannot start advance scope

### ISSUE THREAD

**Issue by horiz00n** [Proto-App/Proto-Android#278]
I've bought the advance scope addon, but I can't activate this feature, please help

![Screenshot_20230905_153704_P R O T O](https://github.com/Proto-App/Proto-Android/assets/144103461/da71f6a9-4bea-4532-958f-504adb7dadc3)
![Screenshot_20230905_153649_P R O T O](https://github.com/Proto-App/Proto-Android/assets/144103461/93d5e333-3e13-46b2-bb83-9fe513f93c39)

**Comment by Proto-App** [comment]
Hello @horiz00n 
Very strange issue. Could you uninstall and install PROTO once again and check this addon?

**Comment by Proto-App** [comment]
@horiz00n any news in your case?

**Comment by horiz00n** [comment]
Do I need to buy this addon again after reinstalling?

Pada tanggal Rab, 6 Sep 2023 05.11, PROTO Team ***@***.***>
menulis:

**Comment by Proto-App** [comment]
No, it should be available for you. Each item is connected to your Google account.

**Comment by Proto-App** [comment]
@horiz00n any news in your case?
