### ISSUE TITLE
Complements isse

### ISSUE THREAD

**Issue by CoffeeSmasher** [Proto-App/Proto-Android#279]
I've bought all the complements in a full price to get them, but, I can't use them all, cause it said that I have to buy them (again). Note: I've buy for all the complements in a single purchase.

**Comment by Proto-App** [comment]
Hello @CoffeeSmasher 
Could you uninstall PROTO and install once again? Sometimes Google needs some time to provide updated purchase state for our app. This action solves 99% of similar issues.

**Comment by Proto-App** [comment]
If you still have this issue then please reopen this ticket
