### ISSUE TITLE
timer 

### ISSUE THREAD

**Issue by Jurgen2003** [Proto-App/Proto-Android#280]
dear @Proto-App 
is it possible with javascript to program a time/timer function so to delay an incoming signal rising and falling delayed if it how does it work 
 gr jurgen

**Comment by Jurgen2003** [comment]
dear @Proto-App 
 i would like to work with times and timers but how does the ( env.gettime() and env.gettimestep()   
   how do they work and what can they do   
 thanks in advance  
greetings jurgen

**Comment by Proto-App** [comment]
Hello @Jurgen2003 

Sorry for delay, we will check this topic and give you some useful solution.

**Comment by Proto-App** [comment]
env.getTime() returns total time accumulated during simulation. It is incremented by your current time step. env.getTimeStep() is current value of timestep. Please check "Pulse source" example. You can find there how to declare global variable and drive output based on timestep:

![js](https://github.com/Proto-App/Proto-Android/assets/63373346/6abbb1f0-8a5b-4a48-8fe3-49f56c4311c6)

**Comment by Jurgen2003** [comment]
dear @Proto-App 
thanks I'm going to work on it but as I indicated before I can't import a circuit via a link and always get the message check your internet but on mobile data ( 4g ) and several Wi-Fi the same problem can you look into it it would be nice if it is solved and the import function I'm waiting for it is on your list I know hopefully again nice features and solutions and components in the next update 
Greetings Jurgen

**Comment by Proto-App** [comment]
@Jurgen2003 

Could you share link with your circuit here? Typically shared items are valid for 6 months.

**Comment by Jurgen2003** [comment]
dear @Proto-App 
I will try a simple circuit and share in whatsapp and mail yet and then share the link to you guys  
 the 6 months I did not know thanks for the info

**Comment by Jurgen2003** [comment]
dear @Proto-App proto 
 the new circuit is importable from the link probably so they are older than 6 months 
 greetings jurgen

**Comment by Proto-App** [comment]
Hi @Jurgen2003 
Ok, thank you. We need to improve error message because now it is confusing when link is obsolete.

**Comment by Proto-App** [comment]
@Jurgen2003 Can we close this thread?

**Comment by Jurgen2003** [comment]
dear @Proto-App  
if there are timers on the list of new components for delaying or delayed switching off may also be 1 timer with multiple possibilities then this can be closed  
greets jurgen

**Comment by Proto-App** [comment]
@Jurgen2003 
You can code this type of IC in JavaScrip addon.

**Comment by Jurgen2003** [comment]
Dear@Proto-App 
How does that code work for timers and can you measure the voltage on one output and use it for the next output
 Greetings jurgen
