### ISSUE TITLE
IC Script Java

### ISSUE THREAD

**Issue by Nuikuitui** [Proto-App/Proto-Android#287]
My PROTO keeps crashing when I try to implement script IC devices or launching their examples. I have an Android. I tried un-installing and reinstalling bit no change.

**Comment by Proto-App** [comment]
Hello @Nuikuitui 
Please share PROTO version and device model.

**Comment by Nuikuitui** [comment]
Version 1.23.0
Android Version 13
Samsung Galaxy, A13 5G, SM-

**Comment by Nuikuitui** [comment]
Version 1.23.0
Android Version 13
Samsung Galaxy, A13 5G, SM-S136DL

**Comment by Nuikuitui** [comment]
Not sure how this got closed, sorry.

**Comment by Proto-App** [comment]
Ok, thank you. Could you share error message during simulation? Maybe post screenshot from script example with output message. You can also share your java script code.

**Comment by Nuikuitui** [comment]
![Screenshot_20231020_161010_Device care~2](https://github.com/Proto-App/Proto-Android/assets/148472801/46ede826-d892-4f7c-ba90-b4a376dbff93)

**Comment by Nuikuitui** [comment]
I can't even get to the coding. When I select the script or play the example the app keeps crashing for IC Script only.

**Comment by Proto-App** [comment]
Ok, we have your crash but probably this is something related with your device. We don't have issue like this on our devices. We will try to figure out how we can debug or fix this issue.

**Comment by Proto-App** [comment]
@Nuikuitui 
Could you check our circuit:
https://www.protosimulator.com/share?circuit=Script_empty_1698233217348
And give use feedback about possible crash.

**Comment by Nuikuitui** [comment]
I clicked on the link and it takes me to your homepage. I'm not seeing a circuit there but a YouTube video, a few pics, and the app download. 
Are you referring to the "examples" in the app?

**Comment by Nuikuitui** [comment]
![Screenshot_20231025_050648_P R O T O](https://github.com/Proto-App/Proto-Android/assets/148472801/b7a669ba-e3a9-4cd1-9976-1410435881a8)

**Comment by Nuikuitui** [comment]
When attempting to run the Script IC in Examples, that too causes the app to crash.

**Comment by Proto-App** [comment]
Our example should be in your workspace. You should be able to import it like on our video:

https://youtu.be/YGS_fxf0E9Q?feature=shared


![Screenshot_20231025-141217.png](https://github.com/Proto-App/Proto-Android/assets/63373346/ed4c63d8-0adb-4b3a-8d4b-6689825dff5b)

**Comment by Nuikuitui** [comment]
Thank you for the video. I had to change a setting to allow the app to open web links in phone app settings. I was able to get the script into my workspace but it crashed again when attempting to open.
![Screenshot_20231025_150140_P R O T O](https://github.com/Proto-App/Proto-Android/assets/148472801/c84f3738-c2aa-47d1-838b-cdd181c37d0f)

![Screenshot_20231025_150024_Device care](https://github.com/Proto-App/Proto-Android/assets/148472801/ee172e59-9634-41a3-95af-060bc32d2978)

**Comment by Proto-App** [comment]
@Nuikuitui Thank you for check. Not good, this is first issue with our script engine and it looks like device specific. We will try to reproduce it on our side with emulator (we don't have A13 5G). By the way we can refund your money because we can't deliver any solution in reasonable time.

**Comment by Nuikuitui** [comment]
No need to refund because the other things are keeping me engaged and creative. This phone and others in the pass like it has only been with me for a year or two and it's garbage and I move on to another (maybe it'll work on my next phone). So no feelings hurt that it's the device.

**Comment by Nuikuitui** [comment]
It's my device. My A13 went for a swim so I'm using my backup phone and the app script IC is working on this cheap Walmart BLU phone.
