### ISSUE TITLE
New Example: Dual H-Bridge Motor

### ISSUE THREAD

**Issue by Amonia69420** [Proto-App/Proto-Android#288]
Dual H-Bridge Motor is a motor driver that can control the direction of the motor, and speed of the motor. The motor is replaced by an inductor. This is the basic example of Dual H-Bridge Motor 
image:
![Circuit 19](https://github.com/Proto-App/Proto-Android/assets/146651777/5eaeccf0-1bf7-4915-b899-e4d46246dc74)
link : https://www.protosimulator.com/share?circuit=L298N_1697859676351

**Comment by Proto-App** [comment]
Thank you for this example! It will be present in version 1.26.0

**Comment by Amonia69420** [comment]
wait, that's wrong image, this is the revision & the link:
![Dual H-bridge motor](https://github.com/Proto-App/Proto-Android/assets/146651777/629e0d05-3de1-489d-9650-1323a798c364)
https://www.protosimulator.com/share?circuit=Dual_H_Bridge_motor_1698108322266

note: IN3 should be swapped with IN4

**Comment by Amonia69420** [comment]
thanks for adding that to proto

**Comment by Proto-App** [comment]
Thank you for this example @Amonia69420 !
