### ISSUE TITLE
bug wiht opamp  

### ISSUE THREAD

**Issue by Jurgen2003** [Proto-App/Proto-Android#290]
Dear @Proto-App 
  I am getting stuck and getting this error message what does this mean and furthermore at the opamp I noticed that the min voltage is fluctuating when the voltage at the input is lower than the minus 

![Screenshot_20231025_151550_P R O T O.jpg](https://github.com/Proto-App/Proto-Android/assets/128260279/eed5886b-afe8-4cb4-a1c6-f5c7bd4ba8d4)

**Comment by Proto-App** [comment]
Hello @Jurgen2003 
It looks like you would like to use function "clamp" in script but it is not defined.

**Comment by Jurgen2003** [comment]
Dear@Proto-App 
And what does that mean and how do you do it ?
 Greets jurgen

**Comment by Proto-App** [comment]
You can use clamp only if you define function with name "clamp". You can learn about functions at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
