### ISSUE TITLE
Fix Bug Capacitors

### ISSUE THREAD

**Issue by Cutty8856** [Proto-App/Proto-Android#295]
Hello, I'd like to report a bug. When capacitors are connected in parallel, a short circuit error pops up. I'm working on a capacitive power supply circuit. Could you please fix this issue? Thanks a lot!

![Image](https://github.com/Proto-App/Proto-Android/assets/151804957/bff2b9f5-1691-405c-9881-0c6a8d985da2)

**Comment by Proto-App** [comment]
Hello @Cutty8856 

This behavior is correct because PROTO has ideal model of capacitor. Please add small resistors or set "Wires resistance" from the right menu.

**Comment by Cutty8856** [comment]
Thank you very much for the help
