### ISSUE TITLE
cloning and sharing

### ISSUE THREAD

**Issue by Ashwin-droid** [Proto-App/Proto-Android#3]
please make that you can clone projects and also share it with other people. for eg you just simulated a **star connection** and now you want to simulate **delta connection** then you wouldn't have to **start fresh** with fine tuning everything.

**Comment by Proto-App** [comment]
Thanks for feedback. Cloning will be first feature on our TODO list.
Sharing requires accounts, it will be available in future but only in paid addon.

**Comment by Proto-App** [comment]
@Ashwin-droid 
You can use copy feature in version 0.18.0
