### ISSUE TITLE
Improvements That can be done

### ISSUE THREAD

**Issue by Radhekrishna121** [Proto-App/Proto-Android#30]
1) Please Introduce Dependent sources 
2) Allow Fixing the values of sources manually by 
     keypad 
3) In AC circuits please show peak value of 
     currentt and voltage across elements and also
     should have an option of showing RMS 
     values 
4) When we are simulating more than one graph 
     The labels of values for 2nd graph are missing 
     from the Y-Axis 
5) rest is good

**Comment by Proto-App** [comment]
All options are present in current version.
