### ISSUE TITLE
How do electric sources work exactly?

### ISSUE THREAD

**Issue by Sureshot14** [Proto-App/Proto-Android#309]
So I am a little confused and frustrated by the electric sources, specifically DC. I am wondering if there is a way to set the voltage source and max current. The DC source seems to only set the voltage and gives a virtually unlimited amount of current depending on need. The current source though does not seem to put out a voltage and is not properly affected by resistors. Without both voltage and current you can really simulate a circuit properly. Is there something or some way to do both?

**Comment by Proto-App** [comment]
Hello @Sureshot14 
Yes, you are right. Sources can deliver unlimited currents because we use ideal models without any internal resistances etc.
