### ISSUE TITLE
Improved input controll and missing signed value in graph

### ISSUE THREAD

**Issue by robinhellstrom** [Proto-App/Proto-Android#31]
Would be great if you could add the ability to instead of turning the knob for adjusting parameters the end user would also be able to input the values with the keyboard.

I'm missing a plus och minus symbol in the graphs.

Some more common IC components like analog comparator would be a nice addon.

**Comment by Proto-App** [comment]
Hello @robinhellstrom 
Thanks for feedback. Task related to keyboard input is under development -> https://github.com/Proto-App/Proto-Android/issues/4

**Comment by Proto-App** [comment]
Implemented in https://github.com/Proto-App/Proto-Android/issues/4
