### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by Amp208** [Proto-App/Proto-Android#314]
I find on larger circuits you cannot zoom out to show the full workspace.

**Comment by Proto-App** [comment]
Hello @Amp208 
Thank you for report, we will try to extend visible area.

**Comment by SzinNapalm** [comment]
> I find on larger circuits you cannot zoom out to show the full workspace.

I was struggling with the same issue as well it's one of the most trouble some things to improve

**Comment by Proto-App** [comment]
Implemented in 1.27.0
