### ISSUE TITLE
IC misbehaving

### ISSUE THREAD

**Issue by DanielFigueiredo1992** [Proto-App/Proto-Android#317]
https://github.com/Proto-App/Proto-Android/assets/124630116/17c4c0dc-3676-46cc-a31e-e4956eb44e3b

I'm trying to use IC 7493, but it has two wrong behaviors. It is decreasing rather than increasing. And it is only supposed to increase in the transition from high to low. My file os an vídeo reproducing The steps. Aldo on 4017 carry out PIN( a PIN to do a pulse if The count reach 10) arent working

**Comment by Proto-App** [comment]
Hello @DanielFigueiredo1992 
Thank you for report. We will check both cases.

**Comment by Proto-App** [comment]
@DanielFigueiredo1992 
Yes, you are correct. IC7493 has bug and we need to solve it. 4017 had missing output flag on C0 and it will be fixed in next release.

**Comment by Proto-App** [comment]
@DanielFigueiredo1992 
Fixed in 1.28.0
