### ISSUE TITLE
Useful Features & Details 

### ISSUE THREAD

**Issue by Gilliermo** [Proto-App/Proto-Android#320]
For example, the ability to increase the frequency of more than 1 GHz or lower the frequency to less than 1 pF, etc
And I would also like to have more proto-space for the schemes 
Please add this, I really need it to implement the scheme

**Comment by Proto-App** [comment]
Hello @Gilliermo 
Sure, we will add possibility to set 1pHz-1GHz frequency. In case of space size, PROTO has bigger circuit area from v1.26.0

**Comment by Proto-App** [comment]
@Gilliermo 
Implemented in 1.27.0
