### ISSUE TITLE
Create user accounts

### ISSUE THREAD

**Issue by JosurielCG** [Proto-App/Proto-Android#323]
Recently I've purchased the Bundle Pack and I noticed that the purchase only applies for the device and I can't access the resources that I bought in other devices. 
That make me wonder what would happen if I've need to delete the app or reset my device. I would lose what I've bought?
I think that implementing user accounts would solve that problem, the account will be the one with the benefits and if you're worried about people using and sharing only one account you can make it mandatory to use internet to access the benefits and only one session allowed at the same time.

**Comment by Proto-App** [comment]
Hello @JosurielCG 
All add-ons are by default assigned to your Google account (it is designed by Google). If you use same account on your second device then you should get access to purchased addon.
