### ISSUE TITLE
Regarding addon

### ISSUE THREAD

**Issue by hemanthiiser** [Proto-App/Proto-Android#330]
I purchased analog addaon package and when I updated the app, my addon package was lost. It's asking to purchase again.
Please resolve my issue. 
![Screenshot_20240304-014512](https://github.com/Proto-App/Proto-Android/assets/162056797/6ace641c-6bac-45b6-af28-993705ed17ca)
![Screenshot_20240304-014452](https://github.com/Proto-App/Proto-Android/assets/162056797/bc798403-ca6c-4ba2-a4a3-1d488fefa3c9)

**Comment by Proto-App** [comment]
Hello @hemanthiiser 
As we can see you have available Misc Pack, not Analog.

**Comment by hemanthiiser** [comment]
Thanks for correcting. It's misc pack. Still that also not showing as owner for me. I lost the access. 

![Screenshot_20240304-015429](https://github.com/Proto-App/Proto-Android/assets/162056797/28423ee8-a615-4abc-a3f4-7bca793d4433)

**Comment by hemanthiiser** [comment]
> Hello @hemanthiiser As we can see you have available Misc Pack, not Analog.

Thanks for correcting, still misc pack also I lost.

**Comment by Proto-App** [comment]
Could you share order id (GPA-xxx)? Or account email address?

**Comment by hemanthiiser** [comment]
Email id: hemanthfirms@gmail.com

UPI transaction I'd: 406406949403
![Uploading a2732f7c-c076-4414-8883-38b0a715d6d5_1709495427%20-%2030.00%20To%20Google%20Play%20on%20Google%20Pay.png…]()

**Comment by hemanthiiser** [comment]
I was just about to purchase the bundle pack. But by looking this for just one update, It was risky to purchase. 
Pls also give a solution.

**Comment by Proto-App** [comment]
@hemanthiiser Could you clear app data or uninstall PROTO and install once again?

**Comment by hemanthiiser** [comment]
Thank you for your email. The issue is resolved. I can able to access now.

**Comment by hemanthiiser** [comment]
Will this problem again raises if new update comes?

**Comment by Proto-App** [comment]
@hemanthiiser Good news! Update should not cause any issues with addon. Do you remember this old version numer?

**Comment by hemanthiiser** [comment]
1.26.0 I think.

**Comment by Proto-App** [comment]
Ok, thank you for info.
