### ISSUE TITLE
Script eror 
Hello proto 
 What is the cause of this problem 
 I can't find it 
Regards jurgen


### ISSUE THREAD

**Issue by Jurgen2003** [Proto-App/Proto-Android#331]
Hello proto 
 What is the cause of this problem 
 I can't find it 
Regards jurgen![Screenshot_20240308_163204_Gallery.jpg](https://github.com/Proto-App/Proto-Android/assets/128260279/154c74b3-ae99-4c6f-9176-81e5e3c12c96)

**Comment by Proto-App** [comment]
@Jurgen2003 
Could you share your circuit?

**Comment by Jurgen2003** [comment]
Dear @Proto-App 
I restarted the script and problem is gone 
But is it possible to get into the beta version to. Help with this great app

**Comment by Proto-App** [comment]
Ok.
