### ISSUE TITLE
Circuit Issue 

### ISSUE THREAD

**Issue by tan45degree** [Proto-App/Proto-Android#333]
I am doing with an electrical circuit but after being done with it when I go for simulation the app goes down and doesn't respond.It takes too much time to get fixed again many components go missing after it resumes.

**Comment by Proto-App** [comment]
Hello @tan45degree 
Could you share your circuit?

**Comment by tan45degree** [comment]
https://www.protosimulator.com/share?circuit=Circuit_2_1710965326075

**Comment by Proto-App** [comment]
Please check fixed version: https://www.protosimulator.com/share?circuit=Circuit_2_1710966943601

It looks like transistor caused huge slowdown, we need to investigate it.
