### ISSUE TITLE
proto algorithms need to be fixed

### ISSUE THREAD

**Issue by bellmicheal663** [Proto-App/Proto-Android#34]
proto algorithms need to be fixed before adding new features or components. Common emiter amplifier circuit not work, eventhough bias like a textbook.  The mosfet power follower amplifier (Andrea Ciuffoli etc) circuits are not working and crash all the time.
Please add mirror components feature for bjt and fets. Edit values by textbox and custom setting fontsize for labels
![Screenshot_20210414-083853](https://user-images.githubusercontent.com/82484024/114641911-223cc900-9cfd-11eb-857d-cfdd38107632.png)
![Screenshot_20210414-083923](https://user-images.githubusercontent.com/82484024/114641941-2ec12180-9cfd-11eb-934c-b27fd127929b.png)

**Comment by Proto-App** [comment]
Thank you for report

**Comment by bellmicheal663** [comment]
Can not give correctly predict the operation of any
![Screenshot_20210419-124303](https://user-images.githubusercontent.com/82484024/115187671-edba7a00-a10d-11eb-8605-ee383042a744.png)
 audio power amplifier circuit.

**Comment by Proto-App** [comment]
@bellmicheal663 
Please provide reference waveforms and values related to your circuits, we have to compare them with our algorithm output.

**Comment by bellmicheal663** [comment]
Sorry is not that picture.
![Screenshot_20210419-181850](https://user-images.githubusercontent.com/82484024/115228636-39841800-a13c-11eb-8b3c-d739ad942805.png)

**Comment by Proto-App** [comment]
@bellmicheal663 
Could you provide correct waveforms and values for your circuit? We need to compare differences with reference data.
