### ISSUE TITLE
Desktop or Web Application

### ISSUE THREAD

**Issue by krotow** [Proto-App/Proto-Android#344]
Are you have Proto Desktop or Web Application planned in future? With syncing with phone app through Google Drive etc. I don't know what you are using for development, but some Android frameworks allow to build Web Apps directly from phone apps pretty easy. Honestly it would make prototyping large circuits much easier. Already got fed by trying to run Proto in BlueStacks or Waydroid (ugh).

**Comment by Proto-App** [comment]
Apps like PROTO requires very fast environment to run simulation. Web frameworks are to slow, we only aim in native frameworks. In future you will be able to sync your workspace with personal Google account :)
