### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ayebaleisaacmagezi** [Proto-App/Proto-Android#348]
Hello guys .
So i have really enjoyed using your app.
And I've bought thr misc pack mostly so that I can use the frequency meter.
But what ever I do.
I've failed to get ot to work.
Please help me with atleast a simple tutorial on how to use it

**Comment by Proto-App** [comment]
Hello @ayebaleisaacmagezi 

Thank you for support! We will prepare simple circuit with frequency meter.

**Comment by ayebaleisaacmagezi** [comment]
OK am eagerly waiting

**Comment by Proto-App** [comment]
Please check simple circuit: https://www.protosimulator.com/share?circuit=Frequency_meter_1718219789254

Please import it in PROTO. You have to wait few seconds for frequency meter to sample circuit frequency.
