### ISSUE TITLE
The application closes when I try to add AD633 component

### ISSUE THREAD

**Issue by diegoxze35** [Proto-App/Proto-Android#352]
In any project's application, when I try to add AD633 component the application closes.
And when the application is reopen, the component is not in the work area.

Mi device: Galaxy A01 with Android 11.

**Comment by Proto-App** [comment]
Thank you for report. We will check this case.

**Comment by vinhk7agg** [comment]
> Thank you for report. We will check this case.

**Comment by vinhk7agg** [comment]
> In any project's application, when I try to add AD633 component the application closes.
> And when the application is reopen, the component is not in the work area.
> 
> Mi device: Galaxy A01 with Android 11.
>

**Comment by vinhk7agg** [comment]
> Thank you for report. We will check this case.

**Comment by vinhk7agg** [comment]
> Thank you for report. We will check this case.

- f9ccfe088dc473e8fd162103bab5bff91b09ef1b

**Comment by Proto-App** [comment]
Hello @diegoxze35 
Do you have issues with AD633?
