### ISSUE TITLE
a short question 

### ISSUE THREAD

**Issue by Jurgen2003** [Proto-App/Proto-Android#354]
dear @Proto-App 
 is it possible to determine in javascript the min , max over 2 inputs for example input 1 has 5 volts and input 2 has 7.5 volts that output 1 then sends out 7.5 but becomes input 1 10 volts output 1 10 volts so over 2 inputs the highest send out   
  if so how does it work I am trying it does not work   
greeting Jurgen

**Comment by Proto-App** [comment]
Hello @Jurgen2003 
Sure, you can use Math.max function:
` let maxVoltage  = Math.max(in0.getVoltage(), in1.getVoltage()); `

**Comment by Jurgen2003** [comment]
Thank you

**Comment by Proto-App** [comment]
@Jurgen2003 
Can we close this topic?

**Comment by Jurgen2003** [comment]
the minumale is then let minVoltage = Math.min(in0.getVoltage(), in1.getVoltage()); 
   thanks and can be closed

**Comment by Proto-App** [comment]
Yes, Math.min for minimum value.
