### ISSUE TITLE
Set variable resistor value error 180 in place of 18 kilo ohm

### ISSUE THREAD

**Issue by PabloMeoniz** [Proto-App/Proto-Android#361]
Set variable resistor value error 180 in place of 18 kilo ohm

The error ocurr in vales show for the chancge variable resistor value.

**Comment by PabloMeoniz** [comment]
![Screenshot_20240808_091729_P R O T O](https://github.com/user-attachments/assets/50e06567-9fe3-49bc-82a5-e75c1cbfbd1d)

**Comment by PabloMeoniz** [comment]
180 kh in place of 18 kh.

**Comment by PabloMeoniz** [comment]
![Screenshot_20240808_091935_P R O T O](https://github.com/user-attachments/assets/34c637b6-6a41-442e-9e5c-bfa22c285a5e)
If I chose 180 kh it doesnt insert a 180 kh, insert a 18 kh.

**Comment by Proto-App** [comment]
Thank you for report. We will check it.

**Comment by Proto-App** [comment]
@PabloMeoniz 
Could you record video? We can't reproduce this issue.
