### ISSUE TITLE
App error or my mistake (capacitor)?  

### ISSUE THREAD

**Issue by tryn4x** [Proto-App/Proto-Android#365]
Edit:
I probably have to add a resistor to the capacitor.  Now it's possible.  Excuse me

Quest:
My circuit with the capacitor doesn't work. In other simulations it works. I get the message: capacitor short
 circuited![kondensatorKurzgeschlossen.jpg](https://github.com/user-attachments/assets/21d27679-22b3-4bbb-85d8-b37d57813873)

The capacitor should charge when sw2 is opened and sw1 is closed. And unloaded / discharge when sw1 is open and sw2 is closed

Thx for your time.

Ps:

It works:

![funktionierenderKondensator.jpg](https://github.com/user-attachments/assets/2e13c2f2-c29e-4a86-8014-a75c3e60748a)

**Comment by Proto-App** [comment]
Hello @tryn4x 
Yes, capacitor in PROTO has ideal computation model (without internal resistance). You can add very small resistor in series with capacitor (like 0.01 Ohm) or turn on "Wires resistance" setting from right menu.
