### ISSUE TITLE
IC 4511.

### ISSUE THREAD

**Issue by miksac** [Proto-App/Proto-Android#376]
The IC model implemented in the app is incorrect. For BCD configurations ranging from 1010 to 1111 (i.e. 10 to 15) the 7-segment display should remain black, not show the hexadecimal letters.

**Comment by Proto-App** [comment]
Hello @miksac 
You are correct, thank you for report. We will change this behavior in next release.

**Comment by miksac** [comment]
Glad to have helped.

**Comment by Proto-App** [comment]
@miksac 
Fixed in version 1.34.1
