### ISSUE TITLE
Component moves when error is generated

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#38]
If an error is generated while pressing and holding down on a push switch, the display will move up while the switch stays in place.
Sample video.

https://user-images.githubusercontent.com/75820960/118383947-18daa100-b5c8-11eb-9139-9f9293f28aac.mp4

**Comment by 64-Tesseract** [comment]
This might have been introduced in the fix for #29, where I had an issue with the error notification covering the add, pause, & delete buttons. Now the buttons move up with the notification, but so does the entire workspace.

**Comment by Proto-App** [comment]
Looks like awkward behavior of touch surface. Not a serious bug but definitely case to improve. Thank you for report.

**Comment by Proto-App** [comment]
Fixed in 0.27.0

**Comment by KarlW100** [comment]
Perfect.
