### ISSUE TITLE
Oscilloscope measure controls

### ISSUE THREAD

**Issue by Michael4404** [Proto-App/Proto-Android#381]
I can't use oscilloscope on a tablet: measuring rules do not appear to be under my control: occasionally, the yellow line appears after I click on different parts of screen. But it is random, sometimes it is not appearing at all. Moreover, when I manage to get a yellow line, it is the same random to get the second line to measure the range. I also have no idea if the measuring functionality should work during playback or only on pause. The length in seconds is not matching the length of main time bar. Oscilloscope is a great feature, but it needs to work.
I also wonder if there is scaling functionality?
Samsung Galaxy tab s8, full pack purchased

**Comment by Proto-App** [comment]
Hello @Michael4404 
Could you record video from your device? We have tablet and scope works as expected.
