### ISSUE TITLE
lost purchase of my bundle pack 

### ISSUE THREAD

**Issue by desmo138** [Proto-App/Proto-Android#384]
I had purchased the bundle pack awhile ago and I guess with the last update I no longer have it.. I like this app please fix.

**Comment by Proto-App** [comment]
Hello @desmo138 
Could you share your google account email address and your order ID?

**Comment by desmo138** [comment]
Hello just getting back with you info..
***@***.***
GPA.3335-0742-3430-94925

**Comment by Proto-App** [comment]
Could you uninstall PROTO, install again and check addon availability?

**Comment by desmo138** [comment]
Hello checking in... thanks everyone it all better.. whatever you did
worked.. or didn't do? Probably user error.. Drugs... Teenager...  Anyways,
Love the app.. keep adding.. can't wait to see updates to come...

**Comment by Proto-App** [comment]
@desmo138 Great!
