### ISSUE TITLE
Deleted by error

### ISSUE THREAD

**Issue by ProtoJess** [Proto-App/Proto-Android#385]
I accidentally deleted a circuit while pressing the add to favorites button and I see that there is no way to recover it, also when deleting there is no confirmation with the option to cancel the action, esp could be improved. 

There should be a recycle bin where one could choose what to restore and what not. I think it is very necessary.

**Comment by Proto-App** [comment]
You have to confirm delete action in PROTO, please share your steps to reproduce this behavior.
