### ISSUE TITLE
Short circuit capacitor

### ISSUE THREAD

**Issue by ProtoJess** [Proto-App/Proto-Android#388]
When my circuit requires a capacitor connected directly to the power supply I get the error "short circuit capacitor" before it did not give that error and in other simulators it does not mark it as an error.
In my projects I usually use a capacitor to simulate a rechargeable battery but Proto doesn't allow it.

**Comment by Proto-App** [comment]
PROTO uses ideal capacitor mathematical model without resistance. You have to use small resistor in series or turn on "Wires resistance" from the right menu.

**Comment by ProtoJess** [comment]
Thanks!
