### ISSUE TITLE
Wires attach to center of diodes

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#39]
Doesn't seem to affect anything, just a little annoying when it happens.  If a diode is moved or placed where the center is over an endpoint, it will attach to the point. Must delete the diode or wire to remove.
![diode_attachment](https://user-images.githubusercontent.com/75820960/118418970-38350500-b680-11eb-8438-577c589cd968.jpg)

**Comment by Proto-App** [comment]
Fixed in 0.27.0

**Comment by KarlW100** [comment]
Thank you.
