### ISSUE TITLE
Hartley oscillator problem

### ISSUE THREAD

**Issue by Amonia69420** [Proto-App/Proto-Android#390]
I tried to simulate hartley oscillator with opamp. But it didn't work. What's the problem?
Circuit:
![Hartley_Failed](https://github.com/user-attachments/assets/0bb22a7a-1b70-4878-9b02-7f1a48e31367)

Refrence
![Screenshot_20241129_061246_Electronics Toolbox](https://github.com/user-attachments/assets/8d8f4f2c-a347-4d06-8874-88b1d3ac0e8c)

**Comment by Proto-App** [comment]
Hello @Amonia69420 
It looks like + input is connected to GND on paper but your circuit different.
