### ISSUE TITLE
Requesting 

### ISSUE THREAD

**Issue by Mawethumabizela** [Proto-App/Proto-Android#391]
Can you please add a component a LDR

**Comment by Amonia69420** [comment]
That already exists. If you wondering, the name is photoresistor
![Screenshot_20241202_195357_P R O T O](https://github.com/user-attachments/assets/40f9b8a2-0230-423d-9a54-7330a4071e15)

**Comment by Mawethumabizela** [comment]
Thanks

**Comment by reklaw29** [comment]
Could you add 74LS76?

**Comment by Mawethumabizela** [comment]
I only have 7401 ttl

**Comment by Proto-App** [comment]
@Mawethumabizela You need "Analog" pack to use photoresistor.
