### ISSUE TITLE
Updates and issues

### ISSUE THREAD

**Issue by reklaw29** [Proto-App/Proto-Android#392]
This is still missing a lot of 74xx series Ic chips. What is required to get other ones added? How can I help get more IC's into this program, the platform looks nice and I like that I can use it on my phone. Please let me know, since I bought the complete bundle I would like to make sure it has what I need.

**Comment by reklaw29** [comment]
Also here is a list of issues:

555 timer doesn't work in astable mode
Jk flipflop doesn't clock or toggle

**Comment by Amonia69420** [comment]
timer 555 is indeed work in astable mode. What's wrong with your circuit?
This is my circuit to test it
![Screenshot_20241209_141614_P R O T O](https://github.com/user-attachments/assets/2f80770b-19ae-475d-afe4-a060693f2d85)

**Comment by Proto-App** [comment]
@reklaw29 
In case of new 74xx chips you can use JavaScript pack and code any behavior of TTL family. Regarding your issues, could you share your circuits?
