### ISSUE TITLE
ISSUE AFTER RECENT APP UPDATE 

### ISSUE THREAD

**Issue by Sourav16ee** [Proto-App/Proto-Android#394]
I have bought the full bundle pack of components a long ago and have used them even today...but as I updated the app , all the bundle pack components are not visible any more...only the unpaid version components are available...please let me know how can I fix this problem..looking forward for your kind cooperation..thanks a lot in advance..

**Comment by Daniel15-telecom** [comment]
I have the same problems, my purchased components have disappeared: (

**Comment by Proto-App** [comment]
Hello @Sourav16ee @Reshot14 
Could you uninstall PROTO and install once again? We will check this issue.

**Comment by Proto-App** [comment]
Strange issue, we can't reproduce it on our side.... We had version 1.34.1 with addons and after update to 1.35.0 addons remains available. Could you confirm that steps on your side are similar?

**Comment by Sourav16ee** [comment]
@Proto-App Hello ! I just now uninstalled and then re-installed the app..no change..the same scenario persists...but now the workspace has also got completely deleted...Idk how to recover it...please advise me the way to fix the above mentioned problems..thanks a lot for your cooperation..and btw...I can attach the order number for my bundle pack purchase if it helps you all to solve the problem...lmk if I shall do so or not...
    The app version has got updated to 1.35.0 but the purchased components aren't available anymore .

**Comment by Proto-App** [comment]
@Sourav16ee 
Pleas share your orderID, we will check addons status on our server.

**Comment by Sourav16ee** [comment]
@Proto-App
OrderID : GPA.3386-4672-8577-96052

**Comment by Proto-App** [comment]
@Sourav16ee 
Strange because we can't see any request from your device to our server (in last 7 days), could you clear app data from System settings and run PROTO after that?

**Comment by Sourav16ee** [comment]
@Proto-App 
Just tried clearing the app data from settings but still no change...
The purchase of the bundle pack was done on 13th October , 2023 .

**Comment by Proto-App** [comment]
@Sourav16ee 
We can refund this payment, later on you can try to buy it again. Now we can't find any reason behind this issue.....

**Comment by Manuel-Delsis** [comment]
Hello, I also have the same problem, in my case it only happens when I have more than one Google account on the phone, I explain I have an account where I bought PROTO, and I have another one from work, when I add the work account to my device, my purchase disappears and when I remove it it comes back

**Comment by Proto-App** [comment]
@Manuel-Delsis 
Account from work is your default one? All purchases are provided from Google framework and we don't have any control over it. Maybe there is an option to set default account?

**Comment by Manuel-Delsis** [comment]
As far as I know, no, it is not my main account. Before commenting here, I looked for someone who had a similar problem to mine on Google support and I found this post from a few years ago: https://support.google.com/googleplay/thread/3113460?hl=es. (This one is in Spanish)

And the response this person received was to contact the app developer.

**Comment by Sourav16ee** [comment]
@Proto-App 
Sure...let me know how I can avail the refund...and then I will buy the pack again with it...thank you so much for your kind cooperation.

**Comment by Proto-App** [comment]
Sure, we will revoke access to add-ons and you will get full amount soon.

**Comment by Sourav16ee** [comment]
@Proto-App 
So , the add-ons will get activated on their own or will you send the money through some online transaction mode to re-buy the add-ons ? If online transactions , then let me know the way to do so..
Thanks so much again..

**Comment by Proto-App** [comment]
It will be reverted by Google :) It is in progress. 
![Zrzut ekranu z 2024-12-24 15-00-47](https://github.com/user-attachments/assets/62a9df44-6199-4326-b1b3-7aa102467392)

**Comment by Sourav16ee** [comment]
@Proto-App 
Thank you so much....
