### ISSUE TITLE
 Components disappeared. 

### ISSUE THREAD

**Issue by Daniel15-telecom** [Proto-App/Proto-Android#396]
My components purchased from the app store are not loading, it appears as if I didn't have them but I bought them.

**Comment by Proto-App** [comment]
Hello @Reshot14 
Please share your order ID.

**Comment by Daniel15-telecom** [comment]
ID of package purchase transactions?

**Comment by Proto-App** [comment]
Yes, it starts with GPA- prefix

**Comment by Daniel15-telecom** [comment]
Misc pack: GPA.3337-0816-1305-42291
Digital pack: GPA.3360-0684-9864-46868

**Comment by Proto-App** [comment]
@Reshot14 
We see that your addons are synced with our server at GMT: Wednesday, 18 December 2024 10:29:54.857
Do you still have missing components from MISC or DIGITAL addons?
