### ISSUE TITLE
fine tuning

### ISSUE THREAD

**Issue by Ashwin-droid** [Proto-App/Proto-Android#4]
please make that we can fine tune anything. for eg you want to simulate a **mains ac circuit** then **fine tuning** the frequency to **50hz/60hz** is a **big pain** so make a edittext that we can change instead of the **stupid dial** only. you can **_keep the dial to coarse tune or set the range like hz,khz,mhz,ghz etc_**

**Comment by Proto-App** [comment]
We have a plan to upgrade dial with **fine tuning mode** so you will be able to set desired value easily.

**Comment by 64-Tesseract** [comment]
> please make that we can fine tune anything. for eg you want to simulate a **mains ac circuit** then **fine tuning** the frequency to **50hz/60hz** is a **big pain** so make a edittext that we can change instead of the **stupid dial** only. you can **_keep the dial to coarse tune or set the range like hz,khz,mhz,ghz etc_**

I agree with Ashwin - being able to just type values would be faster than moving your finger around a circle.

**Comment by Proto-App** [comment]
Feature implemented in version 0.24.0

Tap on dial center to show input dialog
![input](https://user-images.githubusercontent.com/63373346/115735108-82c9a700-a38a-11eb-9874-d298f95d00f4.png)
