### ISSUE TITLE
Led issue

### ISSUE THREAD

**Issue by ghost** [Proto-App/Proto-Android#41]
When I use an LED and I burn it out
Even if I've deleted the LED from my circuit i keep getting the notification that it burnt out

**Comment by Proto-App** [comment]
Hello @joupipop 
Could you post screenshot of your circuit? We are trying to reproduce this case but everything works as expected.

**Comment by joupipop** [comment]
> Hello @joupipop 
> Could you post screenshot of your circuit? We are trying to reproduce this case but everything works as expected. 
So I just tired recreating it and actually everything's working
Sorry for the bother
