### ISSUE TITLE
Delete simulation confirmation (Enhancement)

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#43]
Enhancement request. When the directory is displayed to load, copy, delete a simulation and the trash icon is pressed, display yes/no confirmation. Currently the simulation is instantly deleted. If the icon is pressed by accident (wanted to press copy but missed), all is gone.  The trash icon used to delete components and wires does not need the confirmation.

**Comment by Proto-App** [comment]
Thank you for suggestion, we will introduce dialog with yes/no buttons or native Android UI component called Snackbar with undo button like below:
![android-snackbar-with-action-callback-undo](https://user-images.githubusercontent.com/63373346/121038371-89807200-c7b0-11eb-9d7b-b0ac4ba395aa.png)

**Comment by Proto-App** [comment]
Implemented in v0.28.0 (confirmation dialog)
