### ISSUE TITLE
Component request

### ISSUE THREAD

**Issue by UgurkanTech** [Proto-App/Proto-Android#44]
Following logic parts would be nice:
-Multiplexers
-Binary adders
-JK-D-T-SR Flip-flops
-Detailed gates with configurable input counts

Thanks.

**Comment by Proto-App** [comment]
@UgurkanTech 
Multiplexers, adder and flips flops are in PROTO v1.7.0

**Comment by Proto-App** [comment]
Gates with more inputs implemented in 1.12.0
