### ISSUE TITLE
their's something wrong with the cap and mos

### ISSUE THREAD

**Issue by ioroyagami** [Proto-App/Proto-Android#45]
![Screenshot_20210623_210647_com proto circuitsimulator](https://user-images.githubusercontent.com/29149901/123105149-23f7db00-d46a-11eb-967f-8de283901097.jpg)
when T1's on, CAP is charging. T2 should be turned on. But it's not.

**Comment by Proto-App** [comment]
@ioroyagami 
Thank you for report, we will investigate this issue.

**Comment by Proto-App** [comment]
@ioroyagami 
We checked this circuit and it looks ok. When gate of T2 has 15V (from V2 source) then T2 conducts current.
