### ISSUE TITLE
Diode and LED has the same symbol

### ISSUE THREAD

**Issue by HyVong007** [Proto-App/Proto-Android#48]
I want Diode and Led has DIFFERENT symbol, The Led must have its own symbol.
![Screenshot_20210625-125428_P R O T O](https://user-images.githubusercontent.com/20169967/123376315-7cd38a80-d5b4-11eb-98a1-204ae4c49306.jpg)

**Comment by HyVong007** [comment]
LED and Bulb: i feel hard to see if a Led/Bulp is lighting or not ?
How light is it ? May be some animations or some colors will help us easy to see the lighting.

**Comment by Proto-App** [comment]
Yes, it can be confusing. We will add arrows for LED component. 
In case of bulb you have to set enough voltage and wait a moment, bulb should glow:
![bulb](https://user-images.githubusercontent.com/63373346/123411450-c3bf8100-d5b0-11eb-9393-acfe835766d1.jpg)

**Comment by HyVong007** [comment]
Ok thank you. Im case the Led is burned by high current, Led should has another image or animation of Fire. It is the same with Bulp.
And the light of Led should be clearly to see all over the whole circuit. When i look at the whole circuit at some zoom level, i will see immediately the Lighting LED.
 Thank you

**Comment by Proto-App** [comment]
Implemented in version 0.29.0 (LED has different symbol)
