### ISSUE TITLE
step up transformer

### ISSUE THREAD

**Issue by Ashwin-droid** [Proto-App/Proto-Android#5]
why the hell the **transformer is step down** only?? allow it to **step up** too

**Comment by Proto-App** [comment]
Could you explain your issue? You can adjust **ratio** parameter.

**Comment by Ashwin-droid** [comment]
the maximum ratio is 1 so it means 1 is to 1 which is not step up
if i wanted to step up 12vac to 240vac i can't do it

**Comment by Proto-App** [comment]
You can set ratio above 1:1, check out our example: https://drive.google.com/file/d/12TDISRkf_NNkPporpQ76ScPuJVWBeuOV/view?usp=sharing

**Comment by Ashwin-droid** [comment]
i don't have access to your file

**Comment by Proto-App** [comment]
@Ashwin-droid 
Sorry, we set wrong access to this file, please check out once again.

**Comment by Ashwin-droid** [comment]
thanks for the help
