### ISSUE TITLE
Changelog button shouldn't disappear

### ISSUE THREAD

**Issue by 64-Tesseract** [Proto-App/Proto-Android#51]
Just a minor suggestion - I think you should be able to look at the changelog more than once.
Maybe the first time it'll be yellow, but after that it can be white, or it could be accessible in the info screen.

**Comment by Proto-App** [comment]
Sure, we think that info screen will be right place to access changelog again.

**Comment by Proto-App** [comment]
Implemented in version 0.29.0 (tap on version to see changelog)
