### ISSUE TITLE
Unable to solve joule thief circuit

### ISSUE THREAD

**Issue by corbym** [Proto-App/Proto-Android#52]
I am trying to emulate this circuit:

https://www.instructables.com/Joule-Thief-no-IC-and-no-Transformer/

I have set correct values for each component and also tried to compensate for the "perfect" components with extra resistors (not shown) but the circuit "cannot be solved":

![Screenshot_20210630-082651](https://user-images.githubusercontent.com/21261837/123919618-03a1b200-d97d-11eb-88f9-bdf210703796.png)

**Comment by corbym** [comment]
![Screenshot_20210630-082817](https://user-images.githubusercontent.com/21261837/123919840-419ed600-d97d-11eb-95ce-37503f59fef8.png)

**Comment by Proto-App** [comment]
@corbym 
Thank you for report, could you check with slightly lower time step (600ns) and increased LED current limit (100mA)? We don't have reference signal but we assume that LED should blink very fast.

![device-2021-06-30-205248](https://user-images.githubusercontent.com/63373346/124015848-557e2280-d9e5-11eb-9cd7-ea17f148411d.png)

![device-2021-06-30-205310](https://user-images.githubusercontent.com/63373346/124015880-5adb6d00-d9e5-11eb-86fa-5b36b84affa8.png)

**Comment by corbym** [comment]
Yes this works, thanks 👍
