### ISSUE TITLE
hope to add crystal oscillators

### ISSUE THREAD

**Issue by c-y-github** [Proto-App/Proto-Android#53]
Although square-wave generators and sine wave generators are practical and convenient substitutes for crystal oscillators, the circuits associated with crystal oscillators are of great meaning to learners.

**Comment by electron271** [comment]
There's a crystal oscillator demo, why not turn it into a component?

**Comment by Proto-App** [comment]
@c-y-github @electron271 
Crystal is almost ready, it will be present in next version.

**Comment by electron271** [comment]
🎉

**Comment by Proto-App** [comment]
@c-y-github @electron271 
 Implemented in version 1.10.0
