### ISSUE TITLE
Hope you can add loudspeaker and microphone

### ISSUE THREAD

**Issue by c-y-github** [Proto-App/Proto-Android#54]
Sounds like a good idea, doesn't it

**Comment by yeahmoz** [comment]
Yeah a Wav input would be really usefull for guitar pedal and other audio design! I use this feature for that in LT Spice. 
Another would be a frequency/waveform output graph to see the changes through the circuit.

**Comment by Proto-App** [comment]
@yeahmoz @c-y-github 
Audio input and microphone implemented in version 1.7.0
