### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by neail001** [Proto-App/Proto-Android#56]
QOL - 

1. An Undo button
2. A junction point (otherwise it is hard to draw perpendicular connections 

Components-

1. Variable Cap
2. Variable inductor.

* Please allow a slider to be visible for Variable components.

Thank you to your efforts, please add a support link.

**Comment by Proto-App** [comment]
@neail001 
Junction point should be visible in version 0.30.0

**Comment by Proto-App** [comment]
@neail001 
Undo button implemented in 0.32.0
