### ISSUE TITLE
[bug] Artistic Circuit Preview 

### ISSUE THREAD

**Issue by VincentWolf** [Proto-App/Proto-Android#59]
i've some artistic preview Instead of reality :  
![Capture d'écrans_20210813-134130](https://user-images.githubusercontent.com/4598969/129352344-5131a377-22c8-4b1e-9703-18c45ffe4aac.png)

**Comment by Proto-App** [comment]
@VincentWolf 
Please write steps to reproduce this issue. You can give more details like Android version, phone vendor etc.

**Comment by VincentWolf** [comment]
``Device Info v2.5
©ToraLabs
Created on Sun Aug 15 10:54:31 GMT+02:00 2021

DEVICE
-----------------------------------
Model : View2 Plus
Manufacturer : WIKO
Brand : WIKO
Device : W-P210
Board : p210cn
Hardware : qcom
Android Device ID : – Do you Really need it? –
Device Type : GSM
WiFi MAC Address : 44:D3:00:00:00:00
Build Fingerprint : WIKO/W-P210-OPE/W-P210:8.1.0/OPM1.171019.019/androi12:user/release-keys
USB Host : Supported
Google Advertising ID : 7fdaf832-49b6-4dc8-XXX-e18646502dXX
Timezone : Central European Standard Time (GMT+02:00)

SYSTEM
-----------------------------------
Android Version : Android 8.1.0 Oreo
Released Date : December 5, 2017
Code Name : Android 8.1.0 Oreo
Security Patch Level : 2018-12-01
API Level : 27
Bootloader : unknown
Build Number : OPM1.171019.019 release-keys
Baseband : .TA.2.3.c1-00705-8953_GEN_PACK-1
Java VM : 2.1.0
Kernel : 3.18.71-perf
Language : English
OpenGL ES : 3.2
Root Access : No
Treble : Supported
Seamless Updates : Not Supported
SELinux : Unable to determine
System Uptime : 210:49:42
Google Play Services : 21.26.21

CPU
-----------------------------------
Processor Name : Unknown
CPU Hardware : Qualcomm Technologies, Inc SDM450
Supported ABIs : arm64-v8a, armeabi-v7a, armeabi
CPU Architecture : 8 x 1.80 GHz
Cores : 8
CPU Governor : interactive
CPU Type : 64 Bit (aarch64)
CPU Scaling Driver : msm
Frequency : 652 Mhz - 1804 Mhz
Running CPUs : 
   Core 0       1804.80 MHz

   Core 1       1804.80 MHz

   Core 2       1804.80 MHz

   Core 3       1804.80 MHz

   Core 4       1804.80 MHz

   Core 5       1804.80 MHz

   Core 6       1689.60 MHz

   Core 7       1689.60 MHz
CPU Usage : 100%
BogoMIPS : 38.40
Features : fp asimd evtstrm aes pmull sha1 sha2 crc32
Vulkan Support : Supported (1.0)
CPU Family : 
8 x Cortex-A53
CPU Process : 14 nm LPP
GPU Renderer : Adreno (TM) 506
GPU Vendor : Qualcomm
GPU Version : OpenGL ES-CM 1.1
Total GPU Extensions : 35

BATTERY
-----------------------------------
Health : Good
Status : Discharging
Level : 99%
Voltage : 4293 mV
Power Source : Battery
Technology : Li-ion
Temperature : 35.2 °C
Capacity : 4000 mAh

DISPLAY
-----------------------------------
Resolution : 720 x 1512 Pixels
Density : 320 dpi (HDPI)
Font Scale : 1.0
Physical Size : 5.10
Refresh Rate : 60.0 Hz
HDR : Not Supported
HDR Capabilities : None
Brightness Level : 100 %
Brightness Mode : Automatic
Screen Timeout : 120 Seconds
Orientation : Portrait

MEMORY
-----------------------------------
• Random Access Memory

   Total Memory : 3577.3 MB
   Used Memory : 2461.4 MB
   Available Memory : 1115.9 MB


• System Storage

   Total Memory : 3978.2 MB
   Used Memory : 2630.9 MB
   Available Memory : 1347.3 MB


• Internal Storage

   Total Memory : 50.3 GB
   Used Memory : 34.3 GB
   Available Memory : 16.0 GB

RAM Type : LPDDR3 933 MHz
Channels : Single channel

CAMERA
-----------------------------------

• BACK CAMERA     

Aberration Modes : Fast, High Quality
AntiBanding Modes : Off, 60Hz, 50Hz, Auto
Auto Exposure Modes : On, Auto Flash, Always Flash
Compensation Step : 166667/1000000
AutoFocus Modes : Auto, Off, Off, Macro, Continuous Video, Continuous Picture
Effects : Off, Mono, Negative, Solarize, Sepia, Posterize, Whiteboard, Blackboard, Aqua
Scene Modes : Landscape, Snow, Beach, Disabled, Face Priority, Sunset, Night, Portrait, Face Priority, Portrait, Sports, Face Priority, Steady Photo, Face Priority, Night, CandleLight, Face Priority, Action, FireWorks, Face Priority, Landscape, Party, Night Portrait, Theatre, Action, Face Priority, Beach, Face Priority
Video Stabilization Modes : Off, On
Auto White Balance Modes : Auto, Incandescent, Fluorescent, Warm Fluorescent, Daylight, Cloudy Daylight, Twilight, Shade
Maximum Auto Exposure Regions : 10
Maximum Auto Focus Regions : 1
Maximum Auto White Balance Regions : 0
Edge Modes : Not Available
Flash Available : Yes
Hot Pixel Modes : Not Available
Hardware Level : Level 2
Lens Placement : Back
Focal Lengths : 4.23 mm
Optical Stabilization : Not Available
Camera Capabilities : Backward Compatible
Maximum Output Streams : 3
Maximum Output Streams Stalling : 1
Maximum RAW Output Streams : 0
Partial Results : 1
Maximum Digital Zoom : 8.0
Cropping Type : Center Only
Supported Resolutions : 11.81 MP - 3968 x 2976
8.13 MP - 4032 x 2016
8.29 MP - 3840 x 2160
7.99 MP - 3264 x 2448
7.68 MP - 3200 x 2400
7.40 MP - 3952 x 1872
7.01 MP - 3744 x 1872
5.02 MP - 3168 x 1584
5.31 MP - 3072 x 1728
4.38 MP - 3040 x 1440
8.86 MP - 2976 x 2976
6.30 MP - 3648 x 1728
5.04 MP - 2592 x 1944
4.92 MP - 2560 x 1920
3.69 MP - 2560 x 1440
2.80 MP - 2432 x 1152
3.98 MP - 2304 x 1728
4.06 MP - 2688 x 1512
2.65 MP - 2304 x 1152
3.15 MP - 2048 x 1536
2.80 MP - 2432 x 1152
1.71 MP - 1900 x 900
2.07 MP - 1920 x 1080
2.56 MP - 1600 x 1600
2.50 MP - 1824 x 1368
1.92 MP - 1600 x 1200
1.56 MP - 1440 x 1080
1.23 MP - 1280 x 960
0.98 MP - 1280 x 768
1.04 MP - 1440 x 720
0.92 MP - 1280 x 720
1.44 MP - 1200 x 1200
0.79 MP - 1024 x 768
0.48 MP - 800 x 600
0.41 MP - 864 x 480
0.38 MP - 800 x 480
0.35 MP - 720 x 480
0.31 MP - 640 x 480
0.23 MP - 640 x 360
0.31 MP - 480 x 640
0.17 MP - 480 x 360
0.15 MP - 480 x 320
0.10 MP - 352 x 288
0.08 MP - 320 x 240
0.08 MP - 240 x 320
0.03 MP - 176 x 144
0.03 MP - 144 x 176
0.02 MP - 160 x 120
Test Pattern Mode : Off
Sensor Size : 5.5044904 x 4.126218
Pixel Array Size : 3968 x 2976
Timestamp Source : Unknown
Orientation : 90 deg
Face Detection Modes : Off, Simple
Max Face Count : 10
ISO Sensitivity Range : null

• FRONT CAMERA     

Aberration Modes : Fast, High Quality
AntiBanding Modes : Off, 60Hz, 50Hz, Auto
Auto Exposure Modes : On
Compensation Step : 166667/1000000
AutoFocus Modes : Off
Effects : Off, Mono, Negative, Solarize, Sepia, Posterize, Whiteboard, Blackboard, Aqua
Scene Modes : Landscape, Snow, Beach, Disabled, Face Priority, Sunset, Night, Portrait, Face Priority, Portrait, Sports, Face Priority, Steady Photo, Face Priority, Night, CandleLight, Face Priority, Action, FireWorks, Face Priority, Landscape, Party, Night Portrait, Theatre, Action, Face Priority, Beach, Face Priority
Video Stabilization Modes : Off, On
Auto White Balance Modes : Auto, Incandescent, Fluorescent, Warm Fluorescent, Daylight, Cloudy Daylight, Twilight, Shade
Maximum Auto Exposure Regions : 10
Maximum Auto Focus Regions : 0
Maximum Auto White Balance Regions : 0
Edge Modes : Not Available
Flash Available : No
Hot Pixel Modes : Not Available
Hardware Level : Level 2
Lens Placement : Front
Focal Lengths : 3.34 mm
Optical Stabilization : Not Available
Camera Capabilities : Backward Compatible
Maximum Output Streams : 3
Maximum Output Streams Stalling : 1
Maximum RAW Output Streams : 0
Partial Results : 1
Maximum Digital Zoom : 8.0
Cropping Type : Center Only
Supported Resolutions : 7.99 MP - 3264 x 2448
7.68 MP - 3200 x 2400
5.02 MP - 3168 x 1584
5.31 MP - 3072 x 1728
4.38 MP - 3040 x 1440
5.04 MP - 2592 x 1944
4.92 MP - 2560 x 1920
3.69 MP - 2560 x 1440
2.80 MP - 2432 x 1152
3.98 MP - 2304 x 1728
4.06 MP - 2688 x 1512
2.65 MP - 2304 x 1152
3.15 MP - 2048 x 1536
2.80 MP - 2432 x 1152
1.71 MP - 1900 x 900
2.07 MP - 1920 x 1080
2.56 MP - 1600 x 1600
2.50 MP - 1824 x 1368
1.92 MP - 1600 x 1200
1.56 MP - 1440 x 1080
1.23 MP - 1280 x 960
0.98 MP - 1280 x 768
1.04 MP - 1440 x 720
0.92 MP - 1280 x 720
1.44 MP - 1200 x 1200
0.79 MP - 1024 x 768
0.48 MP - 800 x 600
0.41 MP - 864 x 480
0.38 MP - 800 x 480
0.35 MP - 720 x 480
0.31 MP - 640 x 480
0.23 MP - 640 x 360
0.31 MP - 480 x 640
0.17 MP - 480 x 360
0.15 MP - 480 x 320
0.10 MP - 352 x 288
0.08 MP - 320 x 240
0.08 MP - 240 x 320
0.03 MP - 176 x 144
0.03 MP - 144 x 176
0.02 MP - 160 x 120
Test Pattern Mode : Off
Sensor Size : 4.808912 x 3.6043324
Pixel Array Size : 3264 x 2448
Timestamp Source : Unknown
Orientation : 270 deg
Face Detection Modes : Off, Simple
Max Face Count : 10
ISO Sensitivity Range : null

THERMAL
-----------------------------------
bms : 35.0 °C
pa_therm1 : 38.0 °C
xo_therm : 36.0 °C
xo_therm_buf : 36.0 °C
case_therm : 34.0 °C
tsens_tz_sensor1 : 39.1 °C
tsens_tz_sensor2 : 39.1 °C
tsens_tz_sensor3 : 39.4 °C
tsens_tz_sensor4 : 41.4 °C
tsens_tz_sensor5 : 43.3 °C
tsens_tz_sensor6 : 43.0 °C
tsens_tz_sensor7 : 42.4 °C
tsens_tz_sensor8 : 42.7 °C
tsens_tz_sensor9 : 39.8 °C
tsens_tz_sensor10 : 40.4 °C
tsens_tz_sensor11 : 40.1 °C
tsens_tz_sensor12 : 40.4 °C
tsens_tz_sensor13 : 39.8 °C
tsens_tz_sensor14 : 39.1 °C
tsens_tz_sensor15 : 39.1 °C
pm8953_tz : 40.3 °C
pa_therm0 : 44.0 °C
battery : 35.0 °C

SENSORS
-----------------------------------
42 Sensors are available on your device.

• BMI160 Accelerometer

  Vendor : BOSCH
  Power : 0.18mA
  Type : ACCELEROMETER

• BMI160 Accelerometer Uncalibrated

  Vendor : BOSCH
  Power : 0.18mA
  Type : ACCELEROMETER UNCALIBRATED

• AK09918 Magnetometer

  Vendor : AKM
  Power : 1.1mA
  Type : MAGNETIC FIELD

• AK09918 Magnetometer Uncalibrated

  Vendor : AKM
  Power : 1.1mA
  Type : MAGNETIC FIELD UNCALIBRATED

• BMI160 Gyroscope

  Vendor : BOSCH
  Power : 0.9mA
  Type : GYROSCOPE

• BMI160 Gyroscope Uncalibrated

  Vendor : BOSCH
  Power : 0.9mA
  Type : GYROSCOPE UNCALIBRATED

• EPL259x ALS/PS EPL259x

  Vendor : Eminent
  Power : 0.32mA
  Type : PROXIMITY

• EPL259x ALS/PS EPL259x

  Vendor : Eminent
  Power : 0.32mA
  Type : LIGHT

• BMI160 Accelerometer -Wakeup Secondary

  Vendor : BOSCH
  Power : 0.18mA
  Type : ACCELEROMETER

• BMI160 Accelerometer Uncalibrated -Wakeup Secondary

  Vendor : BOSCH
  Power : 0.18mA
  Type : ACCELEROMETER UNCALIBRATED

• AK09918 Magnetometer -Wakeup Secondary

  Vendor : AKM
  Power : 1.1mA
  Type : MAGNETIC FIELD

• AK09918 Magnetometer Uncalibrated -Wakeup Secondary

  Vendor : AKM
  Power : 1.1mA
  Type : MAGNETIC FIELD UNCALIBRATED

• BMI160 Gyroscope -Wakeup Secondary

  Vendor : BOSCH
  Power : 0.9mA
  Type : GYROSCOPE

• BMI160 Gyroscope Uncalibrated -Wakeup Secondary

  Vendor : BOSCH
  Power : 0.9mA
  Type : GYROSCOPE UNCALIBRATED

• EPL259x ALS/PS EPL259x -Non Wakeup Secondary

  Vendor : Eminent
  Power : 0.32mA
  Type : PROXIMITY

• EPL259x ALS/PS EPL259x -Wakeup Secondary

  Vendor : Eminent
  Power : 0.32mA
  Type : LIGHT

• Gravity

  Vendor : QTI
  Power : 1.0799866mA
  Type : GRAVITY

• Linear Acceleration

  Vendor : QTI
  Power : 1.0799866mA
  Type : LINEAR ACCELERATION

• Rotation Vector

  Vendor : QTI
  Power : 1.9999847mA
  Type : ROTATION VECTOR

• Step Detector

  Vendor : QTI
  Power : 0.17999268mA
  Type : STEP DETECTOR

• Step Counter

  Vendor : QTI
  Power : 0.17999268mA
  Type : STEP COUNTER

• Significant Motion Detector

  Vendor : QTI
  Power : 0.17999268mA
  Type : SIGNIFICANT MOTION

• Game Rotation Vector

  Vendor : QTI
  Power : 1.0799866mA
  Type : GAME ROTATION VECTOR

• GeoMagnetic Rotation Vector

  Vendor : QTI
  Power : 1.2890625mA
  Type : GEOMAGNETIC ROTATION VECTOR

• Orientation

  Vendor : QTI
  Power : 1.9999847mA
  Type : ORIENTATION

• Tilt Detector

  Vendor : QTI
  Power : 0.17999268mA
  Type : TILT DETECTOR

• Pick Up Gesture

  Vendor : QTI
  Power : 0.5mA
  Type : PICK UP GESTURE

• Gravity -Wakeup Secondary

  Vendor : QTI
  Power : 1.0799866mA
  Type : GRAVITY

• Linear Acceleration -Wakeup Secondary

  Vendor : QTI
  Power : 1.0799866mA
  Type : LINEAR ACCELERATION

• Rotation Vector -Wakeup Secondary

  Vendor : QTI
  Power : 1.9999847mA
  Type : ROTATION VECTOR

• Step Detector -Wakeup Secondary

  Vendor : QTI
  Power : 0.17999268mA
  Type : STEP DETECTOR

• Step Counter -Wakeup Secondary

  Vendor : QTI
  Power : 0.17999268mA
  Type : STEP COUNTER

• Game Rotation Vector -Wakeup Secondary

  Vendor : QTI
  Power : 1.0799866mA
  Type : GAME ROTATION VECTOR

• GeoMagnetic Rotation Vector -Wakeup Secondary

  Vendor : QTI
  Power : 1.2890625mA
  Type : GEOMAGNETIC ROTATION VECTOR

• Orientation -Wakeup Secondary

  Vendor : QTI
  Power : 1.9999847mA
  Type : ORIENTATION

• AMD

  Vendor : QTI
  Power : 0.17999268mA
  Type : PRIVATE SENSOR

• RMD

  Vendor : QTI
  Power : 0.17999268mA
  Type : PRIVATE SENSOR

• Basic Gestures

  Vendor : QTI
  Power : 0.17999268mA
  Type : PRIVATE SENSOR

• Facing

  Vendor : QTI
  Power : 0.17999268mA
  Type : PRIVATE SENSOR

• Pedometer

  Vendor : QTI
  Power : 0.17999268mA
  Type : PRIVATE SENSOR

• Motion Accel

  Vendor : QTI
  Power : 0.17999268mA
  Type : PRIVATE SENSOR

• Coarse Motion Classifier

  Vendor : QTI
  Power : 0.17999268mA
  Type : PRIVATE SENSOR


INPUT DEVICES
-----------------------------------
• msm8953-snd-card-mtp Button Jack

Input Device : 1
Vendor ID : 0
Product ID : 0
Keyboard Type : Non-Alphabetic
Descriptor : 652d81422a52c35a5a6d7e3b5c5285d3affd5b11
Has Vibrator : false
Sources : 0x101 (Keyboard)

• msm8953-snd-card-mtp Headset Jack

Input Device : 2
Vendor ID : 0
Product ID : 0
Keyboard Type : None
Descriptor : b6a4175a2792b5bb0355f949aea0d2724cfe89f9
Has Vibrator : false

• TP_GESTURE

Input Device : 3
Vendor ID : 0
Product ID : 0
Keyboard Type : Non-Alphabetic
Descriptor : 21f9200e762b371cde7eec41b8ebe7c9ccbea6e6
Has Vibrator : false
Sources : 0x101 (Keyboard)

• qpnp_pon

Input Device : 4
Vendor ID : 0
Product ID : 0
Keyboard Type : Non-Alphabetic
Descriptor : fb60d4f4370f5dbe8267b63d38dea852987571ab
Has Vibrator : false
Sources : 0x101 (Keyboard)

• hall_sensor

Input Device : 5
Vendor ID : 0
Product ID : 0
Keyboard Type : Non-Alphabetic
Descriptor : 9760af4bed025850a5dc1bfb191f031fec4f6499
Has Vibrator : false
Sources : 0x101 (Keyboard)

• gpio-keys

Input Device : 6
Vendor ID : 1
Product ID : 1
Keyboard Type : Non-Alphabetic
Descriptor : 485d69228e24f5e46da1598745890b214130dbc4
Has Vibrator : false
Sources : 0x101 (Keyboard)

• fts_ts

Input Device : 7
Vendor ID : 0
Product ID : 0
Keyboard Type : Non-Alphabetic
Descriptor : a1cc21cba608c55d28d6dd2b1939004df0e0c756
Has Vibrator : false
Sources : 0x1103 (Keyboard, TouchScreen)
Axis : AXIS_X
Range : 719.0
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002
Axis : AXIS_Y
Range : 1511.0
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002
Axis : AXIS_PRESSURE
Range : 1.0
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002
Axis : AXIS_SIZE
Range : 1.0
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002
Axis : AXIS_TOUCH_MAJOR
Range : 1674.6772
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002
Axis : AXIS_TOUCH_MINOR
Range : 1674.6772
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002
Axis : AXIS_TOOL_MAJOR
Range : 1674.6772
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002
Axis : AXIS_TOOL_MINOR
Range : 1674.6772
Resolution : 0.0
Flat : 0.0
Fuzz : 0.0
Source : 0x1002


CODECS
-----------------------------------
• OMX.google.aac.decoder
  audio/mp4a-latm
• OMX.google.amrnb.decoder
  audio/3gpp
• OMX.google.amrwb.decoder
  audio/amr-wb
• OMX.qti.audio.decoder.flac
  audio/flac
• OMX.google.g711.alaw.decoder
  audio/g711-alaw
• OMX.google.g711.mlaw.decoder
  audio/g711-mlaw
• OMX.google.gsm.decoder
  audio/gsm
• OMX.google.mp3.decoder
  audio/mpeg
• OMX.google.opus.decoder
  audio/opus
• OMX.google.raw.decoder
  audio/raw
• OMX.google.vorbis.decoder
  audio/vorbis
• OMX.google.aac.encoder
  audio/mp4a-latm
• OMX.google.amrnb.encoder
  audio/3gpp
• OMX.google.amrwb.encoder
  audio/amr-wb
• OMX.google.flac.encoder
  audio/flac
• OMX.qcom.video.decoder.avc
  video/avc
• OMX.qcom.video.decoder.avc.secure
  video/avc
• OMX.google.h264.decoder
  video/avc
• OMX.qcom.video.decoder.divx
  video/divx
• OMX.qcom.video.decoder.divx311
  video/divx311
• OMX.qcom.video.decoder.divx4
  video/divx4
• OMX.qcom.video.decoder.h263
  video/3gpp
• OMX.google.h263.decoder
  video/3gpp
• OMX.qcom.video.decoder.hevc
  video/hevc
• OMX.qcom.video.decoder.hevc.secure
  video/hevc
• OMX.google.hevc.decoder
  video/hevc
• OMX.qcom.video.decoder.mpeg2
  video/mpeg2
• OMX.qcom.video.decoder.mpeg2.secure
  video/mpeg2
• OMX.qcom.video.decoder.mpeg4
  video/mp4v-es
• OMX.google.mpeg4.decoder
  video/mp4v-es
• OMX.qcom.video.decoder.wmv
  video/x-ms-wmv
• OMX.qcom.video.decoder.vc1
  video/x-ms-wmv
• OMX.qcom.video.decoder.vc1.secure
  video/x-ms-wmv
• OMX.qcom.video.decoder.vp8
  video/x-vnd.on2.vp8
• OMX.google.vp8.decoder
  video/x-vnd.on2.vp8
• OMX.qcom.video.decoder.vp9
  video/x-vnd.on2.vp9
• OMX.google.vp9.decoder
  video/x-vnd.on2.vp9
• OMX.qcom.video.encoder.avc
  video/avc
• OMX.google.h264.encoder
  video/avc
• OMX.qcom.video.encoder.h263
  video/3gpp
• OMX.google.h263.encoder
  video/3gpp
• OMX.qcom.video.encoder.hevc
  video/hevc
• OMX.qcom.video.encoder.mpeg4
  video/mp4v-es
• OMX.google.mpeg4.encoder
  video/mp4v-es
• OMX.qcom.video.encoder.vp8
  video/x-vnd.on2.vp8
• OMX.google.vp8.encoder
  video/x-vnd.on2.vp8

GPU EXTENSIONS
-----------------------------------
GL_EXT_debug_marker
GL_AMD_compressed_ATC_texture
GL_AMD_performance_monitor
GL_APPLE_texture_2D_limited_npot
GL_ARB_vertex_buffer_object
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_format_BGRA8888
GL_EXT_texture_type_2_10_10_10_REV
GL_OES_blend_equation_separate
GL_OES_blend_func_separate
GL_OES_blend_subtract
GL_OES_compressed_ETC1_RGB8_texture
GL_OES_compressed_paletted_texture
GL_OES_depth_texture
GL_OES_depth24
GL_OES_draw_texture
GL_OES_EGL_image
GL_OES_EGL_image_external
GL_OES_framebuffer_object
GL_OES_matrix_palette
GL_OES_packed_depth_stencil
GL_OES_point_size_array
GL_OES_point_sprite
GL_OES_read_format
GL_OES_rgb8_rgba8
GL_OES_stencil_wrap
GL_OES_texture_cube_map
GL_OES_texture_env_crossbar
GL_OES_texture_float
GL_OES_texture_half_float
GL_OES_texture_half_float_linear
GL_OES_texture_npot
GL_OES_texture_mirrored_repeat
GL_QCOM_extended_get
GL_QCOM_tiled_rendering

DEVICE FEATURES
-----------------------------------
android.hardware.sensor.proximity
android.hardware.sensor.accelerometer
android.hardware.faketouch
android.hardware.usb.accessory
android.hardware.telephony.cdma
android.software.backup
android.hardware.touchscreen
android.hardware.touchscreen.multitouch
android.software.print
android.software.activities_on_secondary_displays
android.software.voice_recognizers
android.software.picture_in_picture
android.hardware.fingerprint
android.hardware.sensor.gyroscope
android.hardware.opengles.aep
android.hardware.bluetooth
android.hardware.camera.autofocus
android.hardware.telephony.gsm
android.software.sip.voip
android.hardware.usb.host
android.hardware.audio.output
android.hardware.camera.flash
android.hardware.camera.front
android.hardware.screen.portrait
android.hardware.sensor.stepdetector
android.software.home_screen
android.hardware.microphone
android.software.autofill
android.hardware.bluetooth_le
android.hardware.sensor.compass
android.hardware.touchscreen.multitouch.jazzhand
android.software.app_widgets
android.software.input_methods
android.hardware.sensor.light
android.hardware.vulkan.version
android.software.companion_device_setup
android.software.device_admin
android.hardware.camera
android.hardware.screen.landscape
android.hardware.ram.normal
android.software.managed_users
android.software.webview
android.hardware.sensor.stepcounter
android.hardware.camera.any
android.hardware.vulkan.compute
android.software.connectionservice
android.hardware.touchscreen.multitouch.distinct
android.hardware.location.network
android.software.cts
android.software.sip
com.google.android.apps.dialer.SUPPORTED
android.hardware.wifi.direct
android.software.live_wallpaper
com.tinno.hardware.display.camera_notch
android.hardware.location.gps
android.software.midi
android.hardware.wifi
android.hardware.location
android.hardware.vulkan.level
android.hardware.telephony

DRM INFO
-----------------------------------
• Widevine CDM     
Vendor : Google
Version : v5.1.0-android
Algorithms : AES/CBC/NoPadding,HmacSHA256
System ID : 44455
Security Level : L3
Max HDCP Level : 
Max No. of Sessions : 16
Usage Reporting Support : True
HDCP Level : 

• Clearkey CDM     
Vendor : Google
Version : 1.0
``

**Comment by VincentWolf** [comment]
> @VincentWolf
> Please write steps to reproduce this issue. You can give more details like Android version, phone vendor etc.

I just install this app from Play store and run it... Nothing else... 
My phone hav't any sd cards but he has some linked directories to emulate extern disk space. It's the only idea I had at this time (i send new info if i found it...)

**Comment by VincentWolf** [comment]
Another info :  All pictures in example tab works well.
Visually and after thinking... it's look like a simple problem : 
It's like the width of pictures zones are smaller than preview and when they are drawed, each pictures lines are breaks before the real width and all undisplayed pixels are puts at the start of the next line like "word-warp" in a text app.
It's really displayed like that, after some few seconds of contemplating, I've understand how this app can display this jpeg and after we see this "scrambling", the apk <answer to me> “why you don't understand all my previews pictures? They are the same like all other sprites„..
😅🤣

**Comment by Proto-App** [comment]
We can't reproduce this issue on our devices. Maybe something is wrong with Android driver on Wiko devices, it has pretty old SOC (Qualcomm SDM450)

**Comment by Proto-App** [comment]
Can not reproduce on Nexus 4, Realme Pad, Xiaomi 9T, Xiaomi A2 Lite, Samsung Galaxy TAB
