### ISSUE TITLE
Oscilloscope breaking

### ISSUE THREAD

**Issue by Ashwin-droid** [Proto-App/Proto-Android#6]
I cannot monitor current and voltage. it breaks the program. sol please add current markings to the other side and keep the voltage marking on the left side.

**Comment by Proto-App** [comment]
For now it is not possible to show current and voltage signal on one plot. We are working hard on scope addon and there you will be able to show voltage/current with some analysis (RMS, P-P, MAX, MIN, AVG), see early preview:

![device-2021-01-23-102619](https://user-images.githubusercontent.com/63373346/105574613-095bf180-5d66-11eb-8141-7d8330a345bd.png)
![device-2021-01-23-102653](https://user-images.githubusercontent.com/63373346/105574615-0b25b500-5d66-11eb-9812-68aa39af0cab.png)

**Comment by Ashwin-droid** [comment]
Still no current plot. I am looking forward to having those features. Please don't make it paid

**Comment by JunkMcNuggets** [comment]
> 

Unfortunately, they missed that last tiny bit of your request...

**Comment by Proto-App** [comment]
@JunkMcNuggets  You can use regular scope ;)

**Comment by TS232CZ** [comment]
Is it really possible that average is higher than min and max valueas?
![Screenshot_20220709-173839_P R O T O](https://user-images.githubusercontent.com/5667413/178112704-a52c74c4-29ff-42e9-baad-30f2401e7b2a.jpg)

**Comment by Proto-App** [comment]
@TS232CZ 
It looks like bug, could you share your circuit via mail?

**Comment by TS232CZ** [comment]
> @TS232CZ It looks like bug, could you share your circuit via mail?

Sent, thank you
TS232

**Comment by salahchafai** [comment]
It's been almost two years and it's still impossible to show current and voltage signal on one plot, even with the scope addon! Are there any projections to when we can have this feature?

**Comment by Proto-App** [comment]
@salahchafai 
Sorry for big delay but as you can see we develop more and more components in our app. In incoming version 1.14.0 you can expect more dependent sources. Finally in 1.15.0 (january 2023) we will add current and voltage on one plot, things like fit Y axis and more.

**Comment by Proto-App** [comment]
Implemented in version 1.15.0
