### ISSUE TITLE
Possible solution to optimize generators

### ISSUE THREAD

**Issue by VincentWolf** [Proto-App/Proto-Android#62]
use only one wire generator like PC Circuit Simulator – ISIS - Proteus  –

Because if i don't convert all GND with res, capa Or with some ≈0V ≈0W circuit to create virtual 0 : 
We can OverBurnOurBrain to Understand why, sometimes, some (any) Diode with only one way can sometimes unblock in his two pins...

(i try to help and sort and explain bugs on picture this week, at this time it just a pictures play : 7 errors | or | where his Waldo and his dog "bug" ) 

![Capture d'écrans_20210814-094700](https://user-images.githubusercontent.com/4598969/129499415-c6198b9a-dc79-490b-b43e-4a9d751f40f7.png)
![Capture d'écrans_20210814-094358](https://user-images.githubusercontent.com/4598969/129499418-f20ae9eb-9e89-42f5-996f-607aeed93144.png)
![Capture d'écrans_20210814-094220](https://user-images.githubusercontent.com/4598969/129499420-a54ba09c-c65e-42de-babf-be024beccb0d.png)

![Capture d'écrans_20210814-105200](https://user-images.githubusercontent.com/4598969/129499397-27e5bc15-eb72-4606-bfc7-1b20e1f12abd.png)
![Capture d'écrans_20210814-105135](https://user-images.githubusercontent.com/4598969/129499399-d0fece93-f12e-4389-97d1-efecb13532a2.png)
![Capture d'écrans_20210814-103124](https://user-images.githubusercontent.com/4598969/129499400-ba62b222-090c-43ad-a977-70f649ac5494.png)
![Capture d'écrans_20210814-094212](https://user-images.githubusercontent.com/4598969/129499403-6b876cc1-277b-4714-a115-41cf09c4f1ac.png)
![Capture d'écrans_20210814-094151](https://user-images.githubusercontent.com/4598969/129499404-e1647b83-d7b2-4501-86a1-905aa2556367.png)
![Capture d'écrans_20210814-105332](https://user-images.githubusercontent.com/4598969/129499405-ebc07453-68f7-4cc4-bb1a-c791f13196db.png)
![Capture d'écrans_20210814-094030](https://user-images.githubusercontent.com/4598969/129499407-d13273de-f2b6-4475-b058-c603cb74668a.png)
![Capture d'écrans_20210814-105250](https://user-images.githubusercontent.com/4598969/129499408-43bdf07a-4dee-477a-9228-5e723039e254.png)
![Capture d'écrans_20210814-093955](https://user-images.githubusercontent.com/4598969/129499410-bc5cd769-3a41-49d5-8e94-7e9846eae4e0.png)
![Capture d'écrans_20210814-105245](https://user-images.githubusercontent.com/4598969/129499411-1dff0cc8-99a8-492d-8b20-8fd1aa962d22.png)
![Capture d'écrans_20210814-103027](https://user-images.githubusercontent.com/4598969/129499412-0843de84-052a-429d-9d9b-5b54f89c4cee.png)

**Comment by Proto-App** [comment]
@VincentWolf 
Please make clear description or we will close this issue.
