### ISSUE TITLE
Stop components requests

### ISSUE THREAD

**Issue by Raart** [Proto-App/Proto-Android#65]
1. This way to enrich the components library is not very efficient.
Everytime one has to simulate a circuit one ore more components are missing.
I'd suggest to create a good importing module to enable catching components from other simulators like Spice,  Ltspice etc. at manufacturers sites.
2. a components editor would be either a great tool.

Both suggestions would make this simulator useful, otherwise you will have the trouble of being annoingly requested to work on the construction of  new components again and again and again...
Having to wait for a indefinite amount of time for your precious help everytime a simulation is needed will discourage users to use your really interesting simulator.
My 10 cents.

**Comment by Proto-App** [comment]
Hello

It is not possible to import each IC from spice simulators, some of them have different standards. Also app has to know how to draw component, it is impossible to implement drawing without native android code. We will add more components in addons. 

In case of editor it is on our TODO list called "subcircuits"
