### ISSUE TITLE
Component suggestions/requests

### ISSUE THREAD

**Issue by t4st3r** [Proto-App/Proto-Android#69]
Hi, 
I really enjoy this app. There are a few missing things for me to use it properly: tapped transformer, custom transistor values (not that crucial) and also i encountered this weird MOSFET issue where it's not fully open until about 100V of GS voltage, which is unusual at least. 
Otherwise, thank you for your hard work, this is AFAIK the most accurate and realistic simulator for Android i have ever used.
Have a nice day!

**Comment by caiohamamura** [comment]
Same here, why the MOSFETs don't have a settings button to set the Vth?

**Comment by t4st3r** [comment]
> Same here, why the MOSFETs don't have a settings button to set the Vth?

yeah that would be really nice
