### ISSUE TITLE
led never blows

### ISSUE THREAD

**Issue by Ashwin-droid** [Proto-App/Proto-Android#7]
led lights on 100kv! and also on .starts glowing at 1.5v and fully glows at 3v. I hope i had this led  #sarcasm 
![signal-2021-01-22-110103](https://user-images.githubusercontent.com/58349846/105451146-fed82400-5ca1-11eb-864f-4ff287f37b3f.jpeg)

**Comment by Proto-App** [comment]
Thanks for report, we have this issue on our list.

**Comment by Proto-App** [comment]
@Ashwin-droid 
Implemented in version 0.19.0

**Comment by Ashwin-droid** [comment]
I would love if it was a bit more spectacular like animation of burning
