### ISSUE TITLE
Duplicate changes the Power setting on bulbs

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#71]
Hello!
This one is simple
When duplicating a bulb the power setting goes back to 60W
![Screenshot_20211009-124910](https://user-images.githubusercontent.com/71222618/136665495-d3cf6d66-f94a-4a8c-9661-463124911bdd.png)
![Screenshot_20211009-124914](https://user-images.githubusercontent.com/71222618/136665506-5fabc612-71d4-4cf3-88fb-a3498d510c5b.png)

Extra: Also i would sugest to add tapped transformer and being able to set the secondaries turns individualy on the settings

**Comment by Proto-App** [comment]
Fixed in version 1.0.0
