### ISSUE TITLE
Isn't the bulb like...too not-shiny?

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#72]
I'm not sure if this is a real problem or not but i think is kind of anoying to have the bulbs being so dim when using lower power
![Screenshot_20211013-152040](https://user-images.githubusercontent.com/71222618/137190984-5c24cfa5-ca0a-4f38-900c-94dad019c025.png)
(Image has bulb with 24V 10W configutarion)
I think is just that
I imagine it being like the power option is a power "needed" for it to shine, not power consumed
Also for it being 5k kelvin is quite obscure
This is not really a bug report but a recomendation or petition to make the bulbs have more bright with lower power option

**Comment by Proto-App** [comment]
Improved in 1.4.0. We decided to use only bulb temperature as alpha factor.
