### ISSUE TITLE
Component request SPDT Switch

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#76]
Similar to the Relay , but not trigerret by an external voltage source but direct by the user, pressing it
Irl, we have some of this where we can change the circuit connection to a source
![Screenshots_2021-10-20-16-13-43](https://user-images.githubusercontent.com/71222618/138174622-93374d1e-5372-4920-bc1f-ec23142ab59a.png)

Is actually pretty simple, user pulses it like a switch it connect to a circuit/component/wire, user pulses it again, it connect to a diferent one
I think many people had to use relays to do this on the simulation.
I would consider this a good improvement for circuit building and have more user interaction as many circuit irl have

**Comment by Proto-App** [comment]
Implemented in version 1.0.0
