### ISSUE TITLE
Add examples using new components from add-on packs

### ISSUE THREAD

**Issue by Unfocused** [Proto-App/Proto-Android#79]
I've purchased the bundle pack because the add-ons are useful and also as I wish to support the efforts going into this app (thank you - it's been a very useful learning tool for me).

However, I don't actually know how or why to use some of the new components. The existing examples are a useful learning resource. It'd be great to have additional examples associated with the add-on packs, to demonstrate the usage & utility of the new components.

**Comment by Proto-App** [comment]
@Unfocused 
Thank you for support! Good idea, we will try to cover new addons in next few releases.
