### ISSUE TITLE
Capacitor unable to be set at 100μF

### ISSUE THREAD

**Issue by YukarinnAM** [Proto-App/Proto-Android#81]
I don't know why or how this happens but for some reason
The user is unable to set a Capacitor to 100μF
If you set it manually it automaticly sets to 99μF
![Screenshot_20211109-140709](https://user-images.githubusercontent.com/71222618/140971512-a3338cce-c231-4119-86d7-e652b210a451.png)
This only happens with Writed User Input 
Is really easy to test just create a new simulation, add a capacitor then try to set it to 100μF
It should appear as 100μF but when using the user input setter it shows 99μF
It isn't a bug of amount of chars of that value either
Since you can set it to 101μF

**Comment by Proto-App** [comment]
Thank you for report. Looks like some silly bug... We will check it.

**Comment by YukarinnAM** [comment]
Thanks for your constant support!
Also
I found out that the error is actually a single visual bug
Since i tested the charge/discarge voltage being both idealy at the same time and the result is that there was no discharge difference for a whole μF of difference
Also
Thanks for the whole new content that comes on addons
I'll save some money to support this great app!

**Comment by Proto-App** [comment]
Thank you! Please share app with friends or rate app on Google Play, it can help a lot :+1:  You can expect more new content with incoming releases (also free components)

**Comment by Proto-App** [comment]
Fixed in version 1.1.0
