### ISSUE TITLE
Problems with capacitors

### ISSUE THREAD

**Issue by Sven130889** [Proto-App/Proto-Android#83]
Why is it displayed as an error when I apply capacitors directly to the voltage source or when I connect capacitors in parallel?

Actually, this is possible without any problems in reality.

**Comment by Proto-App** [comment]
Yes, our capacitor model is ideal. It means that it has no internal resistance. We will add wires resistance (setting switch) and then you will be able to connect voltage source with capacitor directly.

**Comment by Proto-App** [comment]
Wire resistance is now available.
