### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by ATurkishMan** [Proto-App/Proto-Android#84]
I love this app. But think adding a light mode switch would perfect the app.

**Comment by Proto-App** [comment]
@ATurkishMan 
Thank you! Do you mean different theme in app like dark/light mode?

**Comment by ATurkishMan** [comment]
Definitely. And I love the speed of the return. Good job. Thank you.

**Comment by ATurkishMan** [comment]
Light mode is a need when to print the results s.s.

**Comment by Proto-App** [comment]
Ok, it is already on our TODO list.

**Comment by Proto-App** [comment]
@ATurkishMan Implemented in v1.8.0
