### ISSUE TITLE
Undo during full screen scope

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#85]
Not sure if this is supposed to be like this but the undo icon remains active in the full screen scope.
![Screenshot_20211113-134436-926](https://user-images.githubusercontent.com/75820960/141657314-79ed7b00-12b5-4f95-aff9-537073e166c5.png)

**Comment by Proto-App** [comment]
It should be hidden. Will be fixed in next release. Thank you for report.

**Comment by Proto-App** [comment]
Fixed in version 1.1.0
