### ISSUE TITLE
Add Ons Bundle and Single Packs

### ISSUE THREAD

**Issue by Sven130889** [Proto-App/Proto-Android#86]
Hi, I hadn't decided to buy the bundle at first and only bought a single pack.

Now I have bought the remaining 3 packs but the bundle is still for sale.

Do I still have all the contens of the bundle?

**Comment by Proto-App** [comment]
@Sven130889 
Theoretically you have all addons and bundle pack covers this case. But bundle pack allows to use future packs (new ones) and in this case we recommend to buy bundle pack (also it cost less than all pack together)
