### ISSUE TITLE
7 segment led

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#88]
When segments are turned off, it takes awhile to fade out. Switching numbers quickly makes it difficult to read.
If this is normal I would like to see the response time adjustable.
Just noticed that the LED Matrix does the same thing.

**Comment by Proto-App** [comment]
Yes, this effect is also present in LED matrix component. Alpha value depends on diode current, it can be visible with bigger time step. We will think about switch to turn off/on this effect or maybe adjustable fade in/out time

**Comment by Proto-App** [comment]
Fixed in 1.4.0. Fade out effect is removed. Maybe in future we will implement some kind of factor to set.
