### ISSUE TITLE
Add standard values sheet in app

### ISSUE THREAD

**Issue by NagaRavi259** [Proto-App/Proto-Android#93]
**Features request**

Add standard values sheet in the app 
![Screenshot_2021-11-21-22-31-49-632_com google android apps docs](https://user-images.githubusercontent.com/53889378/142794475-77ffbe54-7b96-4565-8d62-dce823b98fc1.jpg)

For components

**Comment by Proto-App** [comment]
@NagaRavi259 
Will be implemented in next release.
