### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#94]
The reset icon is acting different. When the simulation is paused, pressing reset will reset but also immediately restarts the simulation. Before it would not restart the simulation, just reset everything. Is this new way correct?

Karl

**Comment by Proto-App** [comment]
@KarlW100 
Yes, we decided to run simulation after reset because it should be more convenient for user. Typically we want to use reset and run simulation because paused circuit with initial state does not give any information.

**Comment by KarlW100** [comment]
Ok, that makes sense.
