### ISSUE TITLE
Capacitance units 

### ISSUE THREAD

**Issue by Agent259** [Proto-App/Proto-Android#96]
Can you add adjustable capacitor units above 999
Right now its only available upto 999 to manual entering
And
Remove mF from the capacitor unit selection it's refer to micro farad μF 
Both are same
![IMG_20211129_022732](https://user-images.githubusercontent.com/53889378/143786093-ae36a9d0-6afe-4169-9eb1-8267d1c67e4a.jpg)
Pico farad pF , nano farad nF, micro farad μF and farad F
Most of the brands use μF as mf

Capacitor unit conversion table
![capacitance-conversion-table](https://user-images.githubusercontent.com/53889378/143786239-e1d90cf9-03ce-4ea3-a53d-2a53f7aea13b.jpeg)

**Comment by Agent259** [comment]
![IMG_20211129_025148](https://user-images.githubusercontent.com/53889378/143786485-d02723d9-c0e9-4b5b-9407-8778e58aff8a.jpg)

**Comment by Proto-App** [comment]
Hello @Agent259 
m - mili -> 0.001
u - micro -> 0.000001

Yes, we have wrong symbol (u -> µ) we will try to improve it.

**Comment by Proto-App** [comment]
Fixed in v1.2.0
